// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Krialys.Common.Literals;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Krialys.Data.EF.Mso
{
    public partial class TRAP_ATTENDUS_PLANIFS
    {
        [Key]
        [Display(Name = "Display_TRAP_ATTENDUS_PLANIFS_TRAP_ATTENDU_PLANIFID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TRAP_ATTENDU_PLANIFID { get; set; }

        [Display(Name = "Display_TRAP_ATTENDUS_PLANIFS_TRA_ATTENDUID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TRA_ATTENDUID { get; set; }

        [Display(Name = "Display_TRAP_ATTENDUS_PLANIFS_TRP_PLANIFID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TRP_PLANIFID { get; set; }

        [Required(ErrorMessage = "{0} is required. Type A for active, I for inactive")]
        [StringLength(1)]
        [Display(Name = "Display_TRAP_ATTENDUS_PLANIFS_TRAP_STATUT", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRAP_STATUT
        {
            get { return _statut; }
            set
            {
                _statut = string.IsNullOrWhiteSpace(value) ? string.Empty : value.Substring(0, 1).ToUpper();
                if (!_statut.ToUpper().Equals(StatusLiteral.Available) && !_statut.ToUpper().Equals(StatusLiteral.Deactivated))
                {
                    _statut = string.Empty;
                }
            }
        }
        private string _statut = string.Empty;

        [Required]
        [Editable(false)]
        [Display(Name = "Display_TRAP_ATTENDUS_PLANIFS_TRAP_DATE_MODIF", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [DisplayFormat(DataFormatString = "g")]
        public DateTime TRAP_DATE_MODIF { get; set; }

       
        [Editable(false)]
        [Display(Name = "Display_TRAP_ATTENDUS_PLANIFS_TTU_MODIFICATEURID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(36)]
        public string TTU_MODIFICATEURID { get; set; }

        // Foreign Keys \\

        [ForeignKey(nameof(TRA_ATTENDUID))]
        [InverseProperty(nameof(TRA_ATTENDUS.TRAP_ATTENDUS_PLANIFS))]
        public virtual TRA_ATTENDUS TRA_ATTENDU { get; set; }
        [ForeignKey(nameof(TRP_PLANIFID))]
        [InverseProperty(nameof(TRP_PLANIFS.TRAP_ATTENDUS_PLANIFS))]
        public virtual TRP_PLANIFS TRP_PLANIF { get; set; }
    }
}