// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Krialys.Data.EF.Mso
{
    [DisplayColumn("TRC_CONTRAT_CODE")]
    public partial class TRC_CONTRATS
    {
        public TRC_CONTRATS()
        {
            TRA_ATTENDUS = new HashSet<TRA_ATTENDUS>();
        }

        [Key]
        [Display(Name = "Display_TRC_CONTRATS_TRC_CONTRATID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TRC_CONTRATID { get; set; }

        [Required]
        [StringLength(255)]
        [Display(Name = "Display_TRC_CONTRATS_TRC_CONTRAT_CODE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRC_CONTRAT_CODE { get; set; }

        [Required]
        [StringLength(1)]
        [Display(Name = "Display_TRC_CONTRATS_TRC_STATUT", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRC_STATUT { get; set; }

        [Required]
        [StringLength(255)]
        [Display(Name = "Display_TRC_CONTRATS_TRC_LIBC", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRC_LIBC { get; set; }

        [StringLength(255)]
        [Display(Name = "Display_TRC_CONTRATS_TRC_LIB", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRC_LIB { get; set; }

        [Required]
        [StringLength(4000)]
        [Display(Name = "Display_TRC_CONTRATS_TRC_DATUM", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRC_DATUM { get; set; }

        [Required]
        [Editable(false)]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "g")]
        [Display(Name = "Display_TRC_CONTRATS_TRC_DATE_CREATION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public DateTime TRC_DATE_CREATION { get; set; }

        [Editable(false)]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "g")]
        [Display(Name = "Display_TRC_CONTRATS_TRC_DATE_MODIF", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public DateTime TRC_DATE_MODIF { get; set; }

        // [Required]
        [Editable(false)]
        [StringLength(36)]
        [Display(Name = "Display_TRC_CONTRATS_TTU_CREATEURID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TTU_CREATEURID { get; set; }

        [Editable(false)]
        [StringLength(36)]
        [Display(Name = "Display_TRC_CONTRATS_TTU_MODIFICATEURID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TTU_MODIFICATEURID { get; set; }

        // Foreign Keys \\

        [InverseProperty("TRC_CONTRAT")]
        public virtual ICollection<TRA_ATTENDUS> TRA_ATTENDUS { get; set; }
    }
}