// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Krialys.Data.EF.Mso
{
    [DisplayColumn("TRC_LIB")]
    public partial class TRC_CRITICITES
    {
        public TRC_CRITICITES()
        {
            TRA_ATTENDUS = new HashSet<TRA_ATTENDUS>();
        }

        [Key]
        [Display(Name = "Display_TRC_CRITICITES_TRC_CRITICITEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TRC_CRITICITEID { get; set; }

        [Required]
        [StringLength(255)]
        [Display(Name = "Display_TRC_CRITICITES_TRC_LIB", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRC_LIB { get; set; }

        [StringLength(255)]
        [Display(Name = "Display_TRC_CRITICITES_TRC_DESCRIPTION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRC_DESCRIPTION { get; set; }

        // Foreign Keys \\

        [InverseProperty("TRC_CRITICITE")]
        public virtual ICollection<TRA_ATTENDUS> TRA_ATTENDUS { get; set; }
    }
}