// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Krialys.Data.EF.Mso
{
    [DisplayColumn("TRNT_LIB")]
    public partial class TRNT_NATURES_TRAITEMENTS
    {
        public TRNT_NATURES_TRAITEMENTS()
        {
            TRA_ATTENDUS = new HashSet<TRA_ATTENDUS>();
        }

        [Key]
        [Display(Name = "Display_TRNT_NATURES_TRAITEMENTS_TRNT_NATURE_TRAITEMENTID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TRNT_NATURE_TRAITEMENTID { get; set; }

        [Required]
        [StringLength(255)]
        [Display(Name = "Display_TRNT_NATURES_TRAITEMENTS_TRNT_LIB", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRNT_LIB { get; set; }

        [StringLength(255)]
        [Display(Name = "Display_TRNT_NATURES_TRAITEMENTS_TRNT_DESCRIPTION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRNT_DESCRIPTION { get; set; }

        // Foreign Keys\\

        [InverseProperty("TRNT_NATURE_TRAITEMENT")]
        public virtual ICollection<TRA_ATTENDUS> TRA_ATTENDUS { get; set; }
    }
}