// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Krialys.Common.Literals;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Krialys.Data.EF.Mso
{
    [DisplayColumn("TRP_PLANIFID")]
    public partial class TRP_PLANIFS
    {
        public TRP_PLANIFS()
        {
            TRAP_ATTENDUS_PLANIFS = new HashSet<TRAP_ATTENDUS_PLANIFS>();
        }

        [Key]
        [Display(Name = "Display_TRP_PLANIFS_TRP_PLANIFID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TRP_PLANIFID { get; set; }

        [Required(ErrorMessage = "{0} is required. Type A for active, I for inactive")]
        [StringLength(1)]
        [Display(Name = "Display_TRP_PLANIFS_TRP_STATUT", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRP_STATUT
        {
            get { return _statut; }
            set
            {
                _statut = string.IsNullOrWhiteSpace(value) ? string.Empty : value.Substring(0, 1).ToUpper();
                if (!_statut.ToUpper().Equals(StatusLiteral.Available) && !_statut.ToUpper().Equals(StatusLiteral.Deactivated))
                {
                    _statut = string.Empty;
                }
            }
        }
        private string _statut = string.Empty;

        [Required]
        [StringLength(255)]
        [Display(Name = "Display_TRP_PLANIFS_TRP_DESCRIPTION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRP_DESCRIPTION { get; set; }

        [Required]
        [StringLength(255)]
        [Display(Name = "Display_TRP_PLANIFS_TRP_CRON", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRP_CRON { get; set; }

        //[Required]
        [Editable(false)]
        [Display(Name = "Display_TRP_PLANIFS_TTU_CREATEURID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(36)]
        public string TTU_CREATEURID { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "g")]
        [Display(Name = "Display_TRP_PLANIFS_TRP_DATE_DEBUT_PLANIF", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public DateTime TRP_DATE_DEBUT_PLANIF { get; set; }

        [DisplayFormat(DataFormatString = "g")]
        [Display(Name = "Display_TRP_PLANIFS_TRP_DATE_FIN_PLANIF", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public DateTime? TRP_DATE_FIN_PLANIF { get; set; }

        [StringLength(255)]
        [Required]
        [Display(Name = "Display_TRP_PLANIFS_TRP_TIMEZONE_INFOID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRP_TIMEZONE_INFOID { get; set; }


        [Editable(false)]
        [StringLength(36)]
        [Display(Name = "Display_TRP_PLANIFS_TTU_MODIFICATEURID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TTU_MODIFICATEURID { get; set; }

        // Foreign Keys \\

        [InverseProperty("TRP_PLANIF")]
        public virtual ICollection<TRAP_ATTENDUS_PLANIFS> TRAP_ATTENDUS_PLANIFS { get; set; }
    }
}