// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Krialys.Data.EF.Mso
{
    [DisplayColumn("TRR_CODE")]
    public partial class TRR_RESULTATS
    {
        public TRR_RESULTATS()
        {
            TRA_ATTENDUS = new HashSet<TRA_ATTENDUS>();
        }

        [Key]
        [Display(Name = "Display_TRR_RESULTATS_TRR_RESULTATID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TRR_RESULTATID { get; set; }

        [Required]
        [StringLength(255)]
        [Display(Name = "Display_TRR_RESULTATS_TRR_CODE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRR_CODE { get; set; }

        [StringLength(255)]
        [Display(Name = "Display_TRR_RESULTATS_TRR_DESCRIPTION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRR_DESCRIPTION { get; set; }

        // Foreign Keys \\

        [InverseProperty("TRR_RESULTAT")]
        public virtual ICollection<TRA_ATTENDUS> TRA_ATTENDUS { get; set; }
    }
}