// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Krialys.Data.EF.Mso
{
    [DisplayColumn("TRTT_LIB")]
    public partial class TRTT_TECHNOS_TRAITEMENTS
    {
        public TRTT_TECHNOS_TRAITEMENTS()
        {
            TRA_ATTENDUS = new HashSet<TRA_ATTENDUS>();
        }

        [Key]
        [Display(Name = "Display_TRTT_TECHNOS_TRAITEMENTS_TRTT_TECHNO_TRAITEMENTID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TRTT_TECHNO_TRAITEMENTID { get; set; }

        [Required]
        [StringLength(255)]
        [Display(Name = "Display_TRTT_TECHNOS_TRAITEMENTS_TRTT_LIB", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRTT_LIB { get; set; }

        [StringLength(255)]
        [Display(Name = "Display_TRTT_TECHNOS_TRAITEMENTS_TRTT_DESCRIPTION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRTT_DESCRIPTION { get; set; }

        // Foreign Keys \\

        [InverseProperty("TRTT_TECHNO_TRAITEMENT")]
        public virtual ICollection<TRA_ATTENDUS> TRA_ATTENDUS { get; set; }
    }
}