// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Krialys.Data.EF.Univers
{
    [DisplayColumn("TRAS_LABEL")]
    public partial class TRAS_AUTH_SCENARIOS
    {
        public TRAS_AUTH_SCENARIOS()
        {
            TRAPLAS_APPLICATIONS_AUTH_SCENARIOS = new HashSet<TRAPLAS_APPLICATIONS_AUTH_SCENARIOS>();
        }

        [Key]
        [Display(Name = "Display_TRAS_AUTH_SCENARIOS_TRAS_AUTH_SCENARIOID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TRAS_AUTH_SCENARIOID { get; set; }

        [Display(Name = "Display_TRAS_AUTH_SCENARIOS_TRAS_LABEL", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(255)]
        public string TRAS_LABEL { get; set; }

        [Display(Name = "Display_TRAS_AUTH_SCENARIOS_TRAS_DESCRIPTION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(255)]
        public string TRAS_DESCRIPTION { get; set; }

        [InverseProperty("TRAS_AUTH_SCENARIO")]
        public virtual ICollection<TRAPLAS_APPLICATIONS_AUTH_SCENARIOS> TRAPLAS_APPLICATIONS_AUTH_SCENARIOS { get; set; }
    }
}