// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Krialys.Data.EF.Univers
{
    public partial class TRCCL_CATALOG_CLAIMS
    {
        [Key]
        [Display(Name = "Display_TRCCL_CATALOG_CLAIMS_TRCCL_CATALOG_CLAIMID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TRCCL_CATALOG_CLAIMID { get; set; }

        [Display(Name = "Display_TRCCL_CATALOG_CLAIMS_TRCCL_STATUS", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(1)]
        public string TRCCL_STATUS { get; set; }

        [Display(Name = "Display_TRCCL_CATALOG_CLAIMS_TRCL_CLAIMID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TRCL_CLAIMID { get; set; }

        [Display(Name = "Display_TRCCL_CATALOG_CLAIMS_TRCCL_VALUE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(32)]
        public string TRCCL_VALUE { get; set; }

        [Display(Name = "Display_TRCCL_CATALOG_CLAIMS_TRCCL_VALUE_LABEL", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(32)]
        public string TRCCL_VALUE_LABEL { get; set; }

        [Display(Name = "Display_TRCCL_CATALOG_CLAIMS_TRCCL_DESCRIPTION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(255)]
        public string TRCCL_DESCRIPTION { get; set; }


        [Display(Name = "Display_TRCCL_CATALOG_CLAIMS_TRCCL_KIND", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(1)]
        public string TRCCL_KIND { get; set; }

        [ForeignKey(nameof(TRCL_CLAIMID))]
        [InverseProperty(nameof(TRCL_CLAIMS.TRCCL_CATALOG_CLAIMS))]
        public virtual TRCL_CLAIMS TRCL_CLAIM { get; set; }

    }
}