// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Krialys.Data.EF.Univers
{
    [DisplayColumn("TRCLI_LABEL")]
    public partial class TRCLI_CLIENTAPPLICATIONS
    {
        public TRCLI_CLIENTAPPLICATIONS()
        {
            TRCLICL_CLIENTAPPLICATIONS_CLAIMS = new HashSet<TRCLICL_CLIENTAPPLICATIONS_CLAIMS>();
            TRAPLAS_APPLICATIONS_AUTH_SCENARIOS = new HashSet<TRAPLAS_APPLICATIONS_AUTH_SCENARIOS>();
            TRUCL_USERS_CLAIMS = new HashSet<TRUCL_USERS_CLAIMS>();
        }

        [Key]
        [Display(Name = "Display_TRCLI_CLIENTAPPLICATIONS_TRCLI_CLIENTAPPLICATIONID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TRCLI_CLIENTAPPLICATIONID { get; set; }

        [Display(Name = "Display_TRCLI_CLIENTAPPLICATIONS_TRCLI_LABEL", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Editable(false)]
        [StringLength(255)]
        public string TRCLI_LABEL { get; set; }

        [Display(Name = "Display_TRCLI_CLIENTAPPLICATIONS_TRCLI_DESCRIPTION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Editable(false)]
        [StringLength(255)]
        public string TRCLI_DESCRIPTION { get; set; }

       [Display(Name = "Display_TRCLI_CLIENTAPPLICATIONS_TRCLI_STATUS", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(1)]
        public string TRCLI_STATUS { get; set; }

        [Display(Name = "Display_TRCLI_CLIENTAPPLICATIONS_TRCLI_AUTH_PUBLIC", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(36)]
        public string TRCLI_AUTH_PUBLIC { get; set; }

        [Display(Name = "Display_TRCLI_CLIENTAPPLICATIONS_TRCLI_AUTH_SECRET", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(36)]
        public string TRCLI_AUTH_SECRET { get; set; }

        [InverseProperty("TRCLI_CLIENTAPPLICATION")]
        public virtual ICollection<TRCLICL_CLIENTAPPLICATIONS_CLAIMS> TRCLICL_CLIENTAPPLICATIONS_CLAIMS { get; set; }


        [InverseProperty("TRCLI_CLIENTAPPLICATION")]
        public virtual ICollection<TRAPLAS_APPLICATIONS_AUTH_SCENARIOS> TRAPLAS_APPLICATIONS_AUTH_SCENARIOS { get; set; }

        [InverseProperty("TRCLI_CLIENTAPPLICATION")]
        public virtual ICollection<TRUCL_USERS_CLAIMS> TRUCL_USERS_CLAIMS { get; set; }

    }
}