// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Krialys.Data.EF.Univers
{
    [DisplayColumn("TRCL_CLAIM_NAME")]
    public partial class TRCL_CLAIMS
    {
        public TRCL_CLAIMS()
        {
            TRCLICL_CLIENTAPPLICATIONS_CLAIMS = new HashSet<TRCLICL_CLIENTAPPLICATIONS_CLAIMS>();
            TRUCL_USERS_CLAIMS = new HashSet<TRUCL_USERS_CLAIMS>();
            TRCCL_CATALOG_CLAIMS = new HashSet<TRCCL_CATALOG_CLAIMS>();
        }

        [Key]
        [Display(Name = "Display_TRCL_CLAIMS_TRCL_CLAIMID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TRCL_CLAIMID { get; set; }

        [Display(Name = "Display_TRCL_CLAIMS_TRCL_STATUS", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(1)]
        public string TRCL_STATUS { get; set; }

        [Display(Name = "Display_TRCL_CLAIMS_TRCL_CLAIM_NAME", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Editable(false)]
        [StringLength(32)]
        public string TRCL_CLAIM_NAME { get; set; }

        [Display(Name = "Display_TRCL_CLAIMS_TRCL_CLAIM_DESCRIPTION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Editable(false)]
        [StringLength(255)]
        public string TRCL_CLAIM_DESCRIPTION { get; set; }
       
        [StringLength(1)]
        [Display(Name = "Display_TRCL_CLAIMS_TRCLI_MULTIVALUE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRCLI_MULTIVALUE { get; set; }

        [InverseProperty("TRCL_CLAIM")]
        public virtual ICollection<TRCLICL_CLIENTAPPLICATIONS_CLAIMS> TRCLICL_CLIENTAPPLICATIONS_CLAIMS { get; set; }
        [InverseProperty("TRCL_CLAIM")]
        public virtual ICollection<TRUCL_USERS_CLAIMS> TRUCL_USERS_CLAIMS { get; set; }
        [InverseProperty("TRCL_CLAIM")]
        public virtual ICollection<TRCCL_CATALOG_CLAIMS> TRCCL_CATALOG_CLAIMS { get; set; }

    }
}