// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace Krialys.Data.EF.Univers
{
    [Index("TRU_LOGIN", Name = "IX_TRU_LOGIN_TRU_USERS", IsUnique = true)]
    [Index("TRU_NAME", "TRU_FIRST_NAME", Name = "IX_TRU_FULLNAME_TRU_USERS", IsUnique = true)]

    [DisplayColumn("TRU_FULLNAME", "TRU_FULLNAME")]
    public partial class TRU_USERS
    {
        public TRU_USERS()
        {
            TRUCL_USERS_CLAIMS = new HashSet<TRUCL_USERS_CLAIMS>();
            TTAU_AUTHENTIFICATIONS = new HashSet<TTAU_AUTHENTIFICATIONS>();
            TEM_ETAT_MASTERSTRU_RESPONSABLE_FONCTIONNEL = new HashSet<TEM_ETAT_MASTERS>();
            TEM_ETAT_MASTERSTRU_RESPONSABLE_TECHNIQUE = new HashSet<TEM_ETAT_MASTERS>();
            TE_ETATSTRU_ENV_VIERGE_AUTEUR = new HashSet<TE_ETATS>();
            TE_ETATSTRU_DECLARANT = new HashSet<TE_ETATS>();

            /*habilitation */
            VDTFH_HABILITATION = new HashSet<VDTFH_HABILITATIONS>();
            TH_HABILITATION = new HashSet<TH_HABILITATIONS>();

            TRU_INITIALISATION_AUTEUR_TH_HABILITATION = new HashSet<TH_HABILITATIONS>();
            TRU_MAJ_AUTEUR_TH_HABILITATION = new HashSet<TH_HABILITATIONS>();

            TUTE_USER_TEAM = new HashSet<TUTE_USER_TEAMS>();

            TCMD_COMMANDES_TRU_COMMANDITAIRE = new HashSet<TCMD_COMMANDES>();
            TCMD_COMMANDES_TRU_EXPLOITANT = new HashSet<TCMD_COMMANDES>();

            TCMD_SP_SUIVI_PHASES_TRU_AUTEUR_MODIF = new HashSet<TCMD_SP_SUIVI_PHASES>();
            TCMD_DA_DEMANDES_ASSOCIEES_TRU_AUTEUR = new HashSet<TCMD_DA_DEMANDES_ASSOCIEES>();
        }

        [Key]
        [Display(Name = "Display_TRU_USERS_TRU_USERID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(36)]
        public string TRU_USERID { get; set; } = Guid.NewGuid().ToString("N");

        [Required]
        [Display(Name = "Display_TRU_USERS_TRU_STATUS", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(1)]
        [RegularExpression("[AI]", ErrorMessage = "Only 'A' or 'I' values are allowed.")]
        public string TRU_STATUS { get; set; }

        [Required]
        [Display(Name = "Display_TRU_USERS_TRU_LOGIN", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(50)]
        public string TRU_LOGIN { get; set; }

        [Display(Name = "Display_TRU_USERS_TRU_PWD", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(100)]
        [Editable(false)]
        public string TRU_PWD { get; set; }

        [Required]
        [Display(Name = "Display_TRU_USERS_TRU_NAME", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(50)]
        public string TRU_NAME { get; set; }

        [Required]
        [Display(Name = "Display_TRU_USERS_TRU_FIRST_NAME", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(50)]
        public string TRU_FIRST_NAME { get; set; }

        [Display(Name = "Display_TRU_USERS_TRU_FULLNAME", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Editable(false)]
        public string TRU_FULLNAME { get; set; }

        [Display(Name = "Display_TRU_USERS_TRU_EMAIL", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [EmailAddress]
        [StringLength(64)]
        public string TRU_EMAIL { get; set; }

        // is user allowed to connect without LDAP authent then only with local user/pwd 
        [Display(Name = "Display_TRU_USERS_TRU_ALLOW_INTERNAL_AUTH", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public Boolean TRU_ALLOW_INTERNAL_AUTH { get; set; }

        [Required]
        [Display(Name = "Display_TRU_USERS_TRLG_LNGID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRLG_LNGID { get; set; }

        [Required]
        [Display(Name = "Display_TRU_USERS_TRTZ_TZID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRTZ_TZID { get; set; }

        //CHILD 
        [InverseProperty("TRU_USER")]
        public virtual ICollection<TRUCL_USERS_CLAIMS> TRUCL_USERS_CLAIMS { get; set; }

        [InverseProperty("TRU_USER")]
        public virtual ICollection<TTAU_AUTHENTIFICATIONS> TTAU_AUTHENTIFICATIONS { get; set; }

        [InverseProperty(nameof(TEM_ETAT_MASTERS.TRU_RESPONSABLE_FONCTIONNEL))]
        public virtual ICollection<TEM_ETAT_MASTERS> TEM_ETAT_MASTERSTRU_RESPONSABLE_FONCTIONNEL { get; set; }

        [InverseProperty(nameof(TEM_ETAT_MASTERS.TRU_RESPONSABLE_TECHNIQUE))]
        public virtual ICollection<TEM_ETAT_MASTERS> TEM_ETAT_MASTERSTRU_RESPONSABLE_TECHNIQUE { get; set; }

        [InverseProperty(nameof(TE_ETATS.TRU_ENV_VIERGE_AUTEUR))]
        public virtual ICollection<TE_ETATS> TE_ETATSTRU_ENV_VIERGE_AUTEUR { get; set; }

        [InverseProperty(nameof(TE_ETATS.TRU_DECLARANT))]
        public virtual ICollection<TE_ETATS> TE_ETATSTRU_DECLARANT { get; set; }

        /* HABILITATION DEBUT */
        [InverseProperty(nameof(VDTFH_HABILITATIONS.TRU_USER))]
        public virtual ICollection<VDTFH_HABILITATIONS> VDTFH_HABILITATION { get; set; }

        [InverseProperty(nameof(TH_HABILITATIONS.TRU_USER))]
        public virtual ICollection<TH_HABILITATIONS> TH_HABILITATION { get; set; }

        [InverseProperty(nameof(TH_HABILITATIONS.TRU_INITIALISATION_AUTEUR))]
        public virtual ICollection<TH_HABILITATIONS> TRU_INITIALISATION_AUTEUR_TH_HABILITATION { get; set; }

        [InverseProperty(nameof(TH_HABILITATIONS.TRU_MAJ_AUTEUR))]
        public virtual ICollection<TH_HABILITATIONS> TRU_MAJ_AUTEUR_TH_HABILITATION { get; set; }

        [InverseProperty(nameof(TUTE_USER_TEAMS.TRU_USER))]
        public virtual ICollection<TUTE_USER_TEAMS> TUTE_USER_TEAM { get; set; }

        /* HABILITATION FIN */

        /* CMD DEBUT*/
        [InverseProperty(nameof(TCMD_COMMANDES.TRU_COMMANDITAIRE))]
        public virtual ICollection<TCMD_COMMANDES> TCMD_COMMANDES_TRU_COMMANDITAIRE { get; set; }

        [InverseProperty(nameof(TCMD_COMMANDES.TRU_EXPLOITANT))]
        public virtual ICollection<TCMD_COMMANDES> TCMD_COMMANDES_TRU_EXPLOITANT { get; set; }

        [InverseProperty(nameof(TCMD_SP_SUIVI_PHASES.TRU_AUTEUR_MODIF))]
        public virtual ICollection<TCMD_SP_SUIVI_PHASES> TCMD_SP_SUIVI_PHASES_TRU_AUTEUR_MODIF { get; set; }

        [InverseProperty(nameof(TCMD_DA_DEMANDES_ASSOCIEES.TRU_AUTEUR))]
        public virtual ICollection<TCMD_DA_DEMANDES_ASSOCIEES> TCMD_DA_DEMANDES_ASSOCIEES_TRU_AUTEUR { get; set; }

        /* CMD FIN*/
        /*FK */
        [ForeignKey(nameof(TRLG_LNGID))]
        [InverseProperty(nameof(Univers.TR_LNG_Languages.TRU_USERS))]
        public virtual TR_LNG_Languages TR_LNG_Languages { get; set; }

        [ForeignKey(nameof(TRTZ_TZID))]
        [InverseProperty(nameof(TRTZ_TZS.TRU_USER))]
        public virtual TRTZ_TZS TRTZ_TZ { get; set; }
    }
}