// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Krialys.Data.EF.Univers
{
    public partial class TTAU_AUTHENTIFICATIONS
    {
        [Display(Name = "Display_TTAU_AUTHENTIFICATIONS_TTAU_AUTHENTIFICATIONID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Key]
        public int TTAU_AUTHENTIFICATIONID { get; set; }

        [Display(Name = "Display_TTAU_AUTHENTIFICATIONS_TRU_USERID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(36)]
        public string TRU_USERID { get; set; }

        [Display(Name = "Display_TTAU_AUTHENTIFICATIONS_TTAU_AUTH_CODE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(64)]
        public string TTAU_AUTH_CODE { get; set; }

        [Display(Name = "Display_TTAU_AUTHENTIFICATIONS_TTAU_AUTH_CODE_EXP", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [DisplayFormat(DataFormatString = "g", ConvertEmptyStringToNull = false)]
        public DateTimeOffset? TTAU_AUTH_CODE_EXP { get; set; }

        [Display(Name = "Display_TTAU_AUTHENTIFICATIONS_TTAU_REFRESH_TOKEN", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(64)]
        public string TTAU_REFRESH_TOKEN { get; set; }

        [Display(Name = "Display_TTAU_AUTHENTIFICATIONS_TTAU_REFRESH_TOKEN_EXP", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [DisplayFormat(DataFormatString = "g", ConvertEmptyStringToNull = false)]
        public DateTimeOffset? TTAU_REFRESH_TOKEN_EXP { get; set; }

        [ForeignKey(nameof(TRU_USERID))]
        [InverseProperty(nameof(TRU_USERS.TTAU_AUTHENTIFICATIONS))]
        public virtual TRU_USERS TRU_USER { get; set; }
    }
}