// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable



namespace Krialys.Data.EF.Etq
{
    [Index(nameof(TOBF_CODE), Name = "UK_TOBF_OBJ_FORMATS", IsUnique = true)]
    [DisplayColumn("TOBF_LIB")]
    public partial class TOBF_OBJ_FORMATS
    {
        public TOBF_OBJ_FORMATS()
        {
            TOBJE_OBJET_ETIQUETTES = new HashSet<TOBJE_OBJET_ETIQUETTES>();
        }

        [Key]
        public int TOBF_OBJ_FORMATID { get; set; }
		
       [Required(ErrorMessageResourceName = "REQUIRED", ErrorMessageResourceType = typeof(DataAnnotationsResources))]
        [StringLength(20)]
		[Display(Name = "Display_TOBF_OBJ_FORMATS_TOBF_CODE", ResourceType = typeof(DataAnnotationsResources))]
        public string TOBF_CODE { get; set; }
        
		[StringLength(100)]
        [Display(Name = "Display_TOBF_OBJ_FORMATS_TOBF_LIB", ResourceType = typeof(DataAnnotationsResources))]
		public string TOBF_LIB { get; set; }

        [StringLength(250)]
		[Display(Name = "Display_TOBF_OBJ_FORMATS_TOBF_DESC", ResourceType = typeof(DataAnnotationsResources))]
        public string TOBF_DESC { get; set; }

        [InverseProperty("TOBF_OBJ_FORMAT")]
        public virtual ICollection<TOBJE_OBJET_ETIQUETTES> TOBJE_OBJET_ETIQUETTES { get; set; }
    }
}