// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable



namespace Krialys.Data.EF.Etq
{
    [Index(nameof(TPRCP_CODE), nameof(TDOM_DOMAINEID), Name = "UK_TPRCP_PRC_PERIMETRES", IsUnique = true)]
    [DisplayColumn("TPRCP_CODE")]
    public partial class TPRCP_PRC_PERIMETRES
    {
        public TPRCP_PRC_PERIMETRES()
        {
            TETQ_ETIQUETTES = new HashSet<TETQ_ETIQUETTES>();
        }

        public override bool Equals(object obj)
        {
            var item = obj as TPRCP_PRC_PERIMETRES;

            if (item == null)
            {
                return false;
            }

            return this.TPRCP_PRC_PERIMETREID.Equals(item.TPRCP_PRC_PERIMETREID);
        }

        public override int GetHashCode()
        {
            return this.TPRCP_PRC_PERIMETREID.GetHashCode();
        }

        [Key]
        public int TPRCP_PRC_PERIMETREID { get; set; }

        [Required(ErrorMessageResourceName = "REQUIRED", ErrorMessageResourceType = typeof(DataAnnotationsResources))]
        [Display(Name = "Display_TPRCP_PRC_PERIMETRES_TDOM_DOMAINEID", ResourceType = typeof(DataAnnotationsResources))]
        public int? TDOM_DOMAINEID { get; set; }

        [Required(ErrorMessageResourceName = "REQUIRED", ErrorMessageResourceType = typeof(DataAnnotationsResources))]
        [StringLength(32, ErrorMessageResourceName = "MIN_MAX_LENGTH", ErrorMessageResourceType = typeof(DataAnnotationsResources), MinimumLength = 1)]
        [Display(Name = "Display_TPRCP_PRC_PERIMETRES_TPRCP_CODE", ResourceType = typeof(DataAnnotationsResources))]
        public string TPRCP_CODE { get; set; }

        [Required(ErrorMessageResourceName = "REQUIRED", ErrorMessageResourceType = typeof(DataAnnotationsResources))]
        [StringLength(100, ErrorMessageResourceName = "MIN_MAX_LENGTH", ErrorMessageResourceType = typeof(DataAnnotationsResources), MinimumLength = 1)]
        [Display(Name = "Display_TPRCP_PRC_PERIMETRES_TPRCP_LIB", ResourceType = typeof(DataAnnotationsResources))]
        public string TPRCP_LIB { get; set; }

        [StringLength(250)]
        [Display(Name = "Display_TPRCP_PRC_PERIMETRES_TPRCP_DESC", ResourceType = typeof(DataAnnotationsResources))]
        public string TPRCP_DESC { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "g")]
        [Display(Name = "Display_TPRCP_PRC_PERIMETRES_TPRCP_DATE_CREATION", ResourceType = typeof(DataAnnotationsResources))]
        public DateTime TPRCP_DATE_CREATION { get; set; }

        [Required(ErrorMessageResourceName = "REQUIRED", ErrorMessageResourceType = typeof(DataAnnotationsResources))]
        [StringLength(36)]
        [Display(Name = "Display_TPRCP_PRC_PERIMETRES_TRU_ACTEURID", ResourceType = typeof(DataAnnotationsResources))]
        public string TRU_ACTEURID { get; set; } = ""; // OB-367: please use a 'default' value, this avoids exception when used as a 'foreign key'

        [Required(ErrorMessageResourceName = "REQUIRED", ErrorMessageResourceType = typeof(DataAnnotationsResources))]
        [StringLength(1, ErrorMessageResourceName = "REQUIRED", ErrorMessageResourceType = typeof(DataAnnotationsResources), MinimumLength = 1)]
        [Display(Name = "Display_TPRCP_PRC_PERIMETRES_TPRCP_PRM_DYN", ResourceType = typeof(DataAnnotationsResources))]
        public string TPRCP_PRM_DYN { get; set; }


        //Allow this perimetre and child (etiquettes) to be accessible/visible in DTS
        [Display(Name = "Display_TPRCP_PRC_PERIMETRES_TPRCP_ALLOW_DTS_ACCESS", ResourceType = typeof(DataAnnotationsResources))]
        public Boolean TPRCP_ALLOW_DTS_ACCESS { get; set; }
         

        [ForeignKey(nameof(TDOM_DOMAINEID))]
        [InverseProperty("TPRCP_PRC_PERIMETRES")]
        public virtual TDOM_DOMAINES TDOM_DOMAINES { get; set; }


        //NAVIGATION
        [InverseProperty("TPRCP_PRC_PERIMETRE")]
        public virtual ICollection<TETQ_ETIQUETTES> TETQ_ETIQUETTES { get; set; }
    }
}