// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable
namespace Krialys.Data.EF.Etq
{
    public partial class TSEQ_SUIVI_EVENEMENT_ETQS
    {
        [Key]
        [Display(Name = "Display_TSEQ_SUIVI_EVENEMENT_ETQS_TSEQ_SUIVI_EVENEMENT_ETQID", ResourceType = typeof(DataAnnotationsResources))]
        public int TSEQ_SUIVI_EVENEMENT_ETQID { get; set; }

		[Display(Name = "Display_TSEQ_SUIVI_EVENEMENT_ETQS_TETQ_ETIQUETTEID", ResourceType = typeof(DataAnnotationsResources))]
		public int TETQ_ETIQUETTEID { get; set; }

        [Display(Name = "Display_TSEQ_SUIVI_EVENEMENT_ETQS_TTE_TYPE_EVENEMENTID", ResourceType = typeof(DataAnnotationsResources))]

        public int TTE_TYPE_EVENEMENTID { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "g")]
		[Display(Name = "Display_TSEQ_SUIVI_EVENEMENT_ETQS_TSEQ_DATE_EVENEMENT", ResourceType = typeof(DataAnnotationsResources))]
        public DateTime TSEQ_DATE_EVENEMENT { get; set; }

        [StringLength(36)]
        [Display(Name = "Display_TSEQ_SUIVI_EVENEMENT_ETQS_TRU_ACTEURID", ResourceType = typeof(DataAnnotationsResources))]
        public string TRU_ACTEURID { get; set; } = ""; // OB-367: please use a 'default' value, this avoids exception when used as a 'foreign key'
		
		[Display(Name = "Display_TSEQ_SUIVI_EVENEMENT_ETQS_TSEQ_DESC", ResourceType = typeof(DataAnnotationsResources))]
        [StringLength(250)]
        public string TSEQ_DESC { get; set; }

        [Display(Name = "Display_TSEQ_SUIVI_EVENEMENT_ETQS_TSEQ_COMMENTAIRE", ResourceType = typeof(DataAnnotationsResources))]
        [StringLength(250)]
        public string TSEQ_COMMENTAIRE { get; set; }

        [ForeignKey(nameof(TETQ_ETIQUETTEID))]
        [InverseProperty(nameof(TETQ_ETIQUETTES.TSEQ_SUIVI_EVENEMENT_ETQS))]
        public virtual TETQ_ETIQUETTES TETQ_ETIQUETTE { get; set; }
        [ForeignKey(nameof(TTE_TYPE_EVENEMENTID))]
        [InverseProperty(nameof(TTE_TYPE_EVENEMENTS.TSEQ_SUIVI_EVENEMENT_ETQS))]
        public virtual TTE_TYPE_EVENEMENTS TTE_TYPE_EVENEMENT { get; set; }
    }
}