// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable


namespace Krialys.Data.EF.Etq
{
    [Index(nameof(TETQ_ETIQUETTEID), nameof(TSR_ENTREE), Name = "UK_TSR_SUIVI_RESSOURCES", IsUnique = true)]

    public partial class TSR_SUIVI_RESSOURCES
    {
        public TSR_SUIVI_RESSOURCES()
        {

        }

        [Key]
        public int TSR_SUIVI_RESSOURCEID { get; set; }


        [Required(ErrorMessageResourceName = "REQUIRED", ErrorMessageResourceType = typeof(DataAnnotationsResources))]
        [Display(Name = "Display_TSR_SUIVI_RESSOURCES_TETQ_ETIQUETTEID", ResourceType = typeof(DataAnnotationsResources))]
        public int? TETQ_ETIQUETTEID { get; set; }


        [Required(ErrorMessageResourceName = "REQUIRED", ErrorMessageResourceType = typeof(DataAnnotationsResources))]
        [StringLength(40)]
        [MaxLength(40)]
        [Display(Name = "Display_TSR_SUIVI_RESSOURCES_TSR_ENTREE", ResourceType = typeof(DataAnnotationsResources))]
        public string TSR_ENTREE { get; set; }


        [Required(ErrorMessageResourceName = "REQUIRED", ErrorMessageResourceType = typeof(DataAnnotationsResources))]
        [Display(Name = "Display_TSR_SUIVI_RESSOURCES_TTR_TYPE_RESSOURCEID", ResourceType = typeof(DataAnnotationsResources))]
        public int? TTR_TYPE_RESSOURCEID { get; set; }

        [StringLength(200)]
        [MaxLength(200)]
        [Display(Name = "Display_TSR_SUIVI_RESSOURCES_TSR_VALEUR_ENTREE", ResourceType = typeof(DataAnnotationsResources))]
        public string TSR_VALEUR_ENTREE { get; set; }

        [Display(Name = "Display_TSR_SUIVI_RESSOURCES_TETQ_ETIQUETTE_ENTREEID", ResourceType = typeof(DataAnnotationsResources))]
        public int? TETQ_ETIQUETTE_ENTREEID { get; set; }

        [ForeignKey(nameof(TTR_TYPE_RESSOURCEID))]
        [InverseProperty(nameof(TTR_TYPE_RESSOURCES.TSR_SUIVI_RESSOURCES))]
        public virtual TTR_TYPE_RESSOURCES TTR_TYPE_RESSOURCE { get; set; }


        [ForeignKey(nameof(TETQ_ETIQUETTEID))]
        [InverseProperty(nameof(TETQ_ETIQUETTES.TSR_SUIVI_RESSOURCES))]
        public virtual TETQ_ETIQUETTES TETQ_ETIQUETTE { get; set; }

    }
}