// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable


namespace Krialys.Data.EF.Etq
{
    [Index(nameof(TTE_CODE), Name = "UK_TTE_TYPE_EVENEMENTS", IsUnique = true)]
    [DisplayColumn("TTE_LIB")]
    public partial class TTE_TYPE_EVENEMENTS
    {
        public TTE_TYPE_EVENEMENTS()
        {
            TSEQ_SUIVI_EVENEMENT_ETQS = new HashSet<TSEQ_SUIVI_EVENEMENT_ETQS>();
        }

        [Key]
        public int TTE_TYPE_EVENEMENTID { get; set; }

        [Required(ErrorMessageResourceName = "REQUIRED", ErrorMessageResourceType = typeof(DataAnnotationsResources))]
        [StringLength(20)]
        [Display(Name = "Display_TTE_TYPE_EVENEMENTS_TTE_CODE", ResourceType = typeof(DataAnnotationsResources))]
        public string TTE_CODE { get; set; }

        [StringLength(100)]
        [Display(Name = "Display_TTE_TYPE_EVENEMENTS_TTE_LIB", ResourceType = typeof(DataAnnotationsResources))]
        public string TTE_LIB { get; set; }

        [StringLength(250)]
        [Display(Name = "Display_TTE_TYPE_EVENEMENTS_TTE_DESC", ResourceType = typeof(DataAnnotationsResources))]
        public string TTE_DESC { get; set; }

        [InverseProperty("TTE_TYPE_EVENEMENT")]
        public virtual ICollection<TSEQ_SUIVI_EVENEMENT_ETQS> TSEQ_SUIVI_EVENEMENT_ETQS { get; set; }
    }
}