// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    [Index(nameof(TD_DEMANDEID), nameof(TE_ETATID), nameof(TBD_ORDRE_EXECUTION), Name = "IX_TBD_BATCH_DEMANDE$TD_DEMANDES", IsUnique = true)]
    [Index(nameof(TE_ETATID), nameof(TBD_ORDRE_EXECUTION), Name = "IX_TBD_BATCH_DEMANDES$ETAT_BATCH")]
    [Index(nameof(TD_DEMANDEID), Name = "IX_TBD_BATCH_DEMANDES$TD_DEMANDEID")]
    public partial class TBD_BATCH_DEMANDES
    {
        [Display(Name = "Display_TBD_BATCH_DEMANDES_TBD_BATCH_DEMANDEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Key]
        public int TBD_BATCH_DEMANDEID { get; set; }

        [Display(Name = "Display_TBD_BATCH_DEMANDES_TD_DEMANDEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TD_DEMANDEID { get; set; }

        [Display(Name = "Display_TBD_BATCH_DEMANDES_TE_ETATID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TE_ETATID { get; set; }

        [Display(Name = "Display_TBD_BATCH_DEMANDES_TBD_ORDRE_EXECUTION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TBD_ORDRE_EXECUTION { get; set; }

        [Display(Name = "Display_TBD_BATCH_DEMANDES_TBD_EXECUTION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(1)]
        public string TBD_EXECUTION { get; set; }

        [Display(Name = "Display_TBD_BATCH_DEMANDES_TBD_CODE_RETOUR", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TBD_CODE_RETOUR { get; set; }

        [Display(Name = "Display_TBD_BATCH_DEMANDES_TEB_ETAT_BATCHID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TEB_ETAT_BATCHID { get; set; }

        [Display(Name = "Display_TBD_BATCH_DEMANDES_TBD_DATE_DEBUT_EXECUTION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [DisplayFormat(DataFormatString = "g")]
        public DateTime? TBD_DATE_DEBUT_EXECUTION { get; set; }

        [Display(Name = "Display_TBD_BATCH_DEMANDES_TBD_DATE_FIN_EXECUTION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [DisplayFormat(DataFormatString = "g")]
        public DateTime? TBD_DATE_FIN_EXECUTION { get; set; }

        public virtual TD_DEMANDES T { get; set; }
        [ForeignKey(nameof(TEB_ETAT_BATCHID))]
        [InverseProperty(nameof(TEB_ETAT_BATCHS.TBD_BATCH_DEMANDES))]
        public virtual TEB_ETAT_BATCHS TEB_ETAT_BATCH { get; set; }
    }
}