// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    [DisplayColumn("TC_NOM")]
    public partial class TC_CATEGORIES
    {
        public TC_CATEGORIES()
        {
            TEM_ETAT_MASTERS = new HashSet<TEM_ETAT_MASTERS>();
        }

        [Display(Name = "Display_TC_CATEGORIES_TC_CATEGORIEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Key]
        public int TC_CATEGORIEID { get; set; }

        [Display(Name = "Display_TC_CATEGORIES_TC_NOM", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        [StringLength(30)]
        public string TC_NOM { get; set; }

        [Display(Name = "Display_TC_CATEGORIES_TC_DATE_CREATION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [DisplayFormat(DataFormatString = "g")]
        public DateTime TC_DATE_CREATION { get; set; }


        [Display(Name = "Display_TC_CATEGORIES_TRST_STATUTID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        [StringLength(3)]
        public string TRST_STATUTID { get; set; }


        [Display(Name = "Display_TC_CATEGORIES_TC_COMMENTAIRE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(255)]
        public string TC_COMMENTAIRE { get; set; }


        [InverseProperty("TC_CATEGORIE")]
        public virtual ICollection<TEM_ETAT_MASTERS> TEM_ETAT_MASTERS { get; set; }
    }
}