// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Krialys.Common.Literals;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    [Index(nameof(TE_ETATID), Name = "IX_TD_DEMANDES$ETAT")]
    [Index(nameof(TRU_DEMANDEURID), Name = "IX_TD_DEMANDES$NUM_CP")]
    [Index(nameof(TSRV_SERVEURID), Name = "IX_TD_DEMANDES$SERVEUR")]
    [Index(nameof(TD_DEMANDEID), nameof(TE_ETATID), Name = "UK_TD_DEMANDES_TD_DEMANDEID_TE_ETATID", IsUnique = true)]
    [Index(nameof(TD_DEMANDEID), nameof(TE_ETATID), Name = "UQ_TD_DEMANDES", IsUnique = true)]
    public partial class TD_DEMANDES
    {
        public TD_DEMANDES()
        {
            TD_SUSPEND_EXECUTION = StatusLiteral.No; // a rendre modifiable par IHM, si O permet d'eviter "temporairement" qu'une demande soit traitée meme qd son heure d exécution souhaitée sera atteinte  
            TD_IGNORE_RESULT = StatusLiteral.No; //  a rendre modifiable par IHM, si une demande est lancée mais que l utilisateur a identifié que son exécution n etait finalement pas souhaitée

            TBD_BATCH_DEMANDES = new HashSet<TBD_BATCH_DEMANDES>();
            TPD_PREREQUIS_DEMANDES = new HashSet<TPD_PREREQUIS_DEMANDES>();
            TPF_PLANIFS = new HashSet<TPF_PLANIFS>();
            TRD_RESSOURCE_DEMANDES = new HashSet<TRD_RESSOURCE_DEMANDES>();
            TDQ_DEMANDE_QUALIFS = new HashSet<TDQ_DEMANDE_QUALIFS>();
            TDP_DEMANDE_PROCESS = new HashSet<TDP_DEMANDE_PROCESS>();

            TCMD_DA_DEMANDES_ASSOCIEES_TD_DEMANDE = new HashSet<TCMD_DA_DEMANDES_ASSOCIEES>();
             TDC_DEMANDES_COMMANDES_TD_DEMANDE = new HashSet<TDC_DEMANDES_COMMANDES>();
        }

        [Display(Name = "Display_TD_DEMANDES_TD_DEMANDEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Key]
        public int TD_DEMANDEID { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TE_ETATID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TE_ETATID { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_DATE_DEMANDE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [DisplayFormat(DataFormatString = "g")]
        public DateTime TD_DATE_DEMANDE { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_DATE_EXECUTION_SOUHAITEE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [DisplayFormat(DataFormatString = "g")]
        public DateTime? TD_DATE_EXECUTION_SOUHAITEE { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_DATE_PRISE_EN_CHARGE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [DisplayFormat(DataFormatString = "g")]
        public DateTime? TD_DATE_PRISE_EN_CHARGE { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_DATE_LIVRAISON", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [DisplayFormat(DataFormatString = "DD/MM/AAAA")]
        public DateTime? TD_DATE_LIVRAISON { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TRST_STATUTID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        [StringLength(3)]
        public string TRST_STATUTID { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_COMMENTAIRE_UTILISATEUR", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(255)]
        public string TD_COMMENTAIRE_UTILISATEUR { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_INFO_RETOUR_TRAITEMENT", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(255)]
        public string TD_INFO_RETOUR_TRAITEMENT { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TRU_DEMANDEURID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        [StringLength(36)]
        public string TRU_DEMANDEURID { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TSRV_SERVEURID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TSRV_SERVEURID { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TS_SCENARIOID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TS_SCENARIOID { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TRU_GESTIONNAIRE_VALIDEURID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(36)]
        public string TRU_GESTIONNAIRE_VALIDEURID { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_DEMANDE_ORIGINEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TD_DEMANDE_ORIGINEID { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TPF_PLANIF_ORIGINEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TPF_PLANIF_ORIGINEID { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_DUREE_PRODUCTION_REEL", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TD_DUREE_PRODUCTION_REEL { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_COMMENTAIRE_GESTIONNAIRE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        //[StringLength(255)]
        //public string TD_FULL_RESULT_FILE_PATH { get; set; }
        [StringLength(255)]
        public string TD_COMMENTAIRE_GESTIONNAIRE { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_DATE_AVIS_GESTIONNAIRE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [DisplayFormat(DataFormatString = "g")]
        public DateTime? TD_DATE_AVIS_GESTIONNAIRE { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_SEND_MAIL_GESTIONNAIRE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(1)]
        public string TD_SEND_MAIL_GESTIONNAIRE { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_SEND_MAIL_CLIENT", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(1)]
        public string TD_SEND_MAIL_CLIENT { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_RESULT_EXIST_FILE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(1)]
        public string TD_RESULT_EXIST_FILE { get; set; }


        [Display(Name = "Display_TD_DEMANDES_TD_IGNORE_RESULT", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(1)]
        public string TD_IGNORE_RESULT { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_SUSPEND_EXECUTION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(1)]
        public string TD_SUSPEND_EXECUTION { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_RESULT_FILE_SIZE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TD_RESULT_FILE_SIZE { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_RESULT_NB_DOWNLOAD", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TD_RESULT_NB_DOWNLOAD { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_DATE_DERNIER_DOWNLOAD", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [DisplayFormat(DataFormatString = "g")]
        public DateTime? TD_DATE_DERNIER_DOWNLOAD { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_PREREQUIS_DELAI_CHK", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TD_PREREQUIS_DELAI_CHK { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_QUALIF_EXIST_FILE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(1)]
        public string TD_QUALIF_EXIST_FILE { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_QUALIF_BILAN", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TD_QUALIF_BILAN { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_QUALIF_FILE_SIZE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TD_QUALIF_FILE_SIZE { get; set; }

        [Display(Name = "Display_TD_DEMANDES_TD_GUID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(36)]
        public string TD_GUID { get; set; }


 


        [ForeignKey(nameof(TE_ETATID))]
        [InverseProperty(nameof(TE_ETATS.TD_DEMANDES))]
        public virtual TE_ETATS TE_ETAT { get; set; }

        [ForeignKey(nameof(TSRV_SERVEURID))]
        [InverseProperty(nameof(TSRV_SERVEURS.TD_DEMANDES))]
        public virtual TSRV_SERVEURS TSRV_SERVEUR { get; set; }


        

        public virtual ICollection<TBD_BATCH_DEMANDES> TBD_BATCH_DEMANDES { get; set; }

        [InverseProperty("TD_DEMANDE")]
        public virtual ICollection<TPD_PREREQUIS_DEMANDES> TPD_PREREQUIS_DEMANDES { get; set; }

        [InverseProperty("TPF_DEMANDE_ORIGINE")]
        public virtual ICollection<TPF_PLANIFS> TPF_PLANIFS { get; set; }

        public virtual ICollection<TRD_RESSOURCE_DEMANDES> TRD_RESSOURCE_DEMANDES { get; set; }

        [InverseProperty("TD_DEMANDE")]
        public virtual ICollection<TDQ_DEMANDE_QUALIFS> TDQ_DEMANDE_QUALIFS { get; set; }

        [InverseProperty("TD_DEMANDE")]
        public virtual ICollection<TDP_DEMANDE_PROCESS> TDP_DEMANDE_PROCESS { get; set; }

        [InverseProperty("TD_DEMANDE")]
        public virtual ICollection<TCMD_DA_DEMANDES_ASSOCIEES> TCMD_DA_DEMANDES_ASSOCIEES_TD_DEMANDE { get; set; }

        [InverseProperty("TD_DEMANDE")]
        public virtual ICollection<TDC_DEMANDES_COMMANDES> TDC_DEMANDES_COMMANDES_TD_DEMANDE { get; set; }


        
    }
}