// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    public partial class TDC_DEMANDES_COMMANDES
    {
        [Key]
        [Display(Name = "Display_TDC_DEMANDES_COMMANDES_TDC_DEMANDES_COMMANDEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TDC_DEMANDES_COMMANDEID { get; set; }

        [Display(Name = "Display_TDC_DEMANDES_COMMANDES_TCMD_COMMANDEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TCMD_COMMANDEID { get; set; }

        [Display(Name = "Display_TDC_DEMANDES_COMMANDES_TD_DEMANDEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TD_DEMANDEID { get; set; }
   

        [ForeignKey(nameof(TCMD_COMMANDEID))]
        [InverseProperty(nameof( TCMD_COMMANDES.TDC_DEMANDES_COMMANDES))]
        public virtual TCMD_COMMANDES TCMD_COMMANDE { get; set; }

 
        [ForeignKey(nameof(TD_DEMANDEID))]
        [InverseProperty(nameof(TD_DEMANDES.TDC_DEMANDES_COMMANDES_TD_DEMANDE))]
        public virtual TD_DEMANDES TD_DEMANDE { get; set; }

    }
}