// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
     
    public partial class TDQ_DEMANDE_QUALIFS
    {

        [Key]
        [Display(Name = "Display_TDQ_DEMANDE_QUALIFS_TDQ_DEMANDE_QUALIFID", ResourceType = typeof(Resources.DataAnnotationsResources))]

        public int TDQ_DEMANDE_QUALIFID { get; set; }

        [Display(Name = "Display_TDQ_DEMANDE_QUALIFS_TD_DEMANDEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TD_DEMANDEID { get; set; }

        [Display(Name = "Display_TDQ_DEMANDE_QUALIFS_TDQ_NUM_ORDRE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TDQ_NUM_ORDRE { get; set; }


        [Display(Name = "Display_TDQ_DEMANDE_QUALIFS_TDQ_CODE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(30)]
        public string TDQ_CODE { get; set; }


        [Display(Name = "Display_TDQ_DEMANDE_QUALIFS_TDQ_NOM", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(30)]
        public string TDQ_NOM { get; set; }

        [Display(Name = "Display_TDQ_DEMANDE_QUALIFS_TDQ_VALEUR", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TDQ_VALEUR { get; set; }


        [Display(Name = "Display_TDQ_DEMANDE_QUALIFS_TDQ_NATURE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(255)]
        public string TDQ_NATURE { get; set; }

        [Display(Name = "Display_TDQ_DEMANDE_QUALIFS_TDQ_DATASET", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(255)]
        public string TDQ_DATASET { get; set; }

        [Display(Name = "Display_TDQ_DEMANDE_QUALIFS_TDQ_OBJECTIF", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(255)]
        public string TDQ_OBJECTIF { get; set; }

        [Display(Name = "Display_TDQ_DEMANDE_QUALIFS_TDQ_TYPOLOGIE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(255)]
        public string TDQ_TYPOLOGIE { get; set; }

        [Display(Name = "Display_TDQ_DEMANDE_QUALIFS_TDQ_COMMENT", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(255)]
        public string TDQ_COMMENT { get; set; }


        [Display(Name = "Display_TDQ_DEMANDE_QUALIFS_TDQ_DATE_PROD", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [DisplayFormat(DataFormatString = "g")]
        public DateTime? TDQ_DATE_PROD { get; set; }

        [ForeignKey(nameof(TD_DEMANDEID))]
        [InverseProperty(nameof(TD_DEMANDES.TDQ_DEMANDE_QUALIFS))]
        public virtual TD_DEMANDES TD_DEMANDE { get; set; }
    }
}