// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    [Index(nameof(TE_ETATID), Name = "IX_TEB_ETAT_BATCHS$TE_ETATS")]
    [Index(nameof(TEB_ETAT_BATCHID), Name = "IX_TEB_ETAT_BATCHS$TE_ETAT_BATCHS")]
    public partial class TEB_ETAT_BATCHS
    {
        public TEB_ETAT_BATCHS()
        {
            TBD_BATCH_DEMANDES = new HashSet<TBD_BATCH_DEMANDES>();
            TBS_BATCH_SCENARIOS = new HashSet<TBS_BATCH_SCENARIOS>();
        }

        [Key]
        public int TEB_ETAT_BATCHID { get; set; }
        
        [Required]
        public int TE_ETATID { get; set; }

        [StringLength(255)]
        [Display(Name = "Display_TEB_ETAT_BATCHS_TEB_NOM_AFFICHAGE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TEB_NOM_AFFICHAGE { get; set; }
        
        [StringLength(255)]
        [Display(Name = "Display_TEB_ETAT_BATCHS_TEB_DESCR", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TEB_DESCR { get; set; }
       
        [Required]
        [StringLength(255)]
        public string TEB_CMD { get; set; }

        [Required]
        [StringLength(3)]
        [Display(Name = "Display_TEB_ETAT_BATCHS_TRST_STATUTID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRST_STATUTID { get; set; }

        [DisplayFormat(DataFormatString = "g")]
        [Display(Name = "Display_TEB_ETAT_BATCHS_TEB_DATE_CREATION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public DateTime TEB_DATE_CREATION { get; set; }

        [ForeignKey(nameof(TE_ETATID))]
        [InverseProperty(nameof(TE_ETATS.TEB_ETAT_BATCHS))]
        public virtual TE_ETATS TE_ETAT { get; set; }


        [ForeignKey(nameof(TRST_STATUTID))]
        [InverseProperty(nameof(TRST_STATUTS.TEB_ETAT_BATCHS))]
        public virtual TRST_STATUTS TRST_STATUT { get; set; }

        [InverseProperty("TEB_ETAT_BATCH")]
        public virtual ICollection<TBD_BATCH_DEMANDES> TBD_BATCH_DEMANDES { get; set; }
        [InverseProperty("TEB_ETAT_BATCH")]
        public virtual ICollection<TBS_BATCH_SCENARIOS> TBS_BATCH_SCENARIOS { get; set; }
    }
}