// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    [Index(nameof(TE_ETATID), nameof(TL_LOGICIELID), Name = "UQ_TEL_ETAT_LOGICIELS", IsUnique = true)]
    public partial class TEL_ETAT_LOGICIELS
    {
        [Display(Name = "Display_TEL_ETAT_LOGICIELS_TEL_ETAT_LOGICIELID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Key] 
        public int TEL_ETAT_LOGICIELID { get; set; }

        [Display(Name = "Display_TEL_ETAT_LOGICIELS_TE_ETATID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        public int TE_ETATID { get; set; }

        [Display(Name = "Display_TEL_ETAT_LOGICIELS_TL_LOGICIELID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        public int TL_LOGICIELID { get; set; }

        [ForeignKey(nameof(TE_ETATID))]
        [InverseProperty(nameof(TE_ETATS.TEL_ETAT_LOGICIELS))]
        public virtual TE_ETATS TE_ETAT { get; set; }
       
        [ForeignKey(nameof(TL_LOGICIELID))]
        [InverseProperty(nameof(TL_LOGICIELS.TEL_ETAT_LOGICIELS))]
        public virtual TL_LOGICIELS TL_LOGICIEL { get; set; }
    }
}