// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    public partial class TEP_ETAT_PREREQUISS
    {
        public TEP_ETAT_PREREQUISS()
        {
            TPD_PREREQUIS_DEMANDES = new HashSet<TPD_PREREQUIS_DEMANDES>();
            TPS_PREREQUIS_SCENARIOS = new HashSet<TPS_PREREQUIS_SCENARIOS>();
        }

        [Key]
        public int TEP_ETAT_PREREQUISID { get; set; }

        public int TE_ETATID { get; set; }

        [DisplayFormat(DataFormatString = "g")]
        [Display(Name = "Display_TEP_ETAT_PREREQUISS_TEP_DATE_MAJ", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public DateTime? TEP_DATE_MAJ { get; set; }

        [Required]
        [StringLength(3)]
        [Display(Name = "Display_TEP_ETAT_PREREQUISS_TRST_STATUTID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRST_STATUTID { get; set; }

        [Required]
        [StringLength(5)]
        [Display(Name = "Display_TEP_ETAT_PREREQUISS_TEP_NATURE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TEP_NATURE { get; set; }

        [Required]
        [StringLength(255)]
        [Display(Name = "Display_TEP_ETAT_PREREQUISS_TEP_PATH", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TEP_PATH { get; set; }

        [Required]
        [StringLength(255)]
        [Display(Name = "Display_TEP_ETAT_PREREQUISS_TEP_FILEPATTERN", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TEP_FILEPATTERN { get; set; }

        [Required]
        [StringLength(1)]
        [Display(Name = "Display_TEP_ETAT_PREREQUISS_TEP_IS_PATTERN", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TEP_IS_PATTERN { get; set; }

        [StringLength(255)]
        [Display(Name = "Display_TEP_ETAT_PREREQUISS_TEP_COMMENTAIRE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TEP_COMMENTAIRE { get; set; }


        [ForeignKey(nameof(TE_ETATID))]
        [InverseProperty(nameof(TE_ETATS.TEP_ETAT_PREREQUISS))]
        public virtual TE_ETATS TE_ETAT { get; set; }

        [ForeignKey(nameof(TRST_STATUTID))]
        [InverseProperty(nameof(TRST_STATUTS.TEP_ETAT_PREREQUISS))]
        public virtual TRST_STATUTS TRST_STATUT { get; set; }

        [InverseProperty("TEP_ETAT_PREREQUIS")]
        public virtual ICollection<TPD_PREREQUIS_DEMANDES> TPD_PREREQUIS_DEMANDES { get; set; }

        [InverseProperty("TEP_ETAT_PREREQUIS")]
        public virtual ICollection<TPS_PREREQUIS_SCENARIOS> TPS_PREREQUIS_SCENARIOS { get; set; }
    }
}