// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Krialys.Data.EF.Univers
{
    [DisplayColumn("TF_DESCR")]
    public partial class TF_FERMES
    {
        public TF_FERMES()
        {
            TEMF_ETAT_MASTER_FERMES = new HashSet<TEMF_ETAT_MASTER_FERMES>();
            TPUF_PARALLELEU_FERMES = new HashSet<TPUF_PARALLELEU_FERMES>();
        }

        [Display(Name = "Display_TF_FERMES_TF_FERMEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Key]
        public int TF_FERMEID { get; set; }

        [Display(Name = "Display_TF_FERMES_TF_DESCR", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(255)]
        [Required]
        public string TF_DESCR { get; set; }

        [Display(Name = "Display_TF_FERMES_TRST_STATUTID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        [StringLength(3)]
        public string TRST_STATUTID { get; set; }

        [Display(Name = "Display_TF_FERMES_TF_EN_MAINTENANCE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(1)]
        public string TF_EN_MAINTENANCE { get; set; }

        [ForeignKey(nameof(TRST_STATUTID))]
        [InverseProperty(nameof(TRST_STATUTS.TF_FERMES))]
        public virtual TRST_STATUTS TRST_STATUT { get; set; }
        [InverseProperty("TF_FERME")]
        public virtual ICollection<TEMF_ETAT_MASTER_FERMES> TEMF_ETAT_MASTER_FERMES { get; set; }
        [InverseProperty("TF_FERME")]
        public virtual ICollection<TPUF_PARALLELEU_FERMES> TPUF_PARALLELEU_FERMES { get; set; }
    }
}