// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    public partial class TI_INFOS
    {
        [Key]
        public int TI_INFOID { get; set; }

        [DisplayFormat(DataFormatString = "g")]
        public DateTime? TI_DATE { get; set; }
        [StringLength(255)]
        public string TI_MSG { get; set; }
        [StringLength(255)]
        public string TI_MSG_EN { get; set; }
        [Required]
        [StringLength(3)]
        public string TRST_STATUTID { get; set; }
        public byte[] TI_IMG { get; set; }
       
        [DisplayFormat(DataFormatString = "g")]
        public DateTime TI_DT_DEBUT_VALIDITE { get; set; }
        
        [DisplayFormat(DataFormatString = "g")]
        public DateTime? TI_DT_FIN_VALIDITE { get; set; }

        [ForeignKey(nameof(TRST_STATUTID))]
        [InverseProperty(nameof(TRST_STATUTS.TI_INFOS))]
        public virtual TRST_STATUTS TRST_STATUT { get; set; }
    }
}