// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Krialys.Data.EF.Univers
{
    public partial class TL_LOGICIELS
    {
        public TL_LOGICIELS()
        {
            TEL_ETAT_LOGICIELS = new HashSet<TEL_ETAT_LOGICIELS>();
            TSL_SERVEUR_LOGICIELS = new HashSet<TSL_SERVEUR_LOGICIELS>();
        }

        [Display(Name = "Display_TL_LOGICIELS_TL_LOGICIELID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Key]
        public int TL_LOGICIELID { get; set; }

        [Display(Name = "Display_TL_LOGICIELS_TL_NOM_LOGICIEL", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(30)]
        [Required]
        public string TL_NOM_LOGICIEL { get; set; }

        [Display(Name = "Display_TL_LOGICIELS_TL_LOGICIEL_VERSION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(10)]
        public string TL_LOGICIEL_VERSION { get; set; }

        [Display(Name = "Display_TL_LOGICIELS_TL_DATE_LOGICIEL", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [DisplayFormat(DataFormatString = "g")]
        public DateTime? TL_DATE_LOGICIEL { get; set; }

        [Display(Name = "Display_TL_LOGICIELS_TLE_LOGICIEL_EDITEURID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TLE_LOGICIEL_EDITEURID { get; set; }

        [ForeignKey(nameof(TLE_LOGICIEL_EDITEURID))]
        [InverseProperty(nameof(TLE_LOGICIEL_EDITEURS.TL_LOGICIELS))]
        public virtual TLE_LOGICIEL_EDITEURS TLE_LOGICIEL_EDITEUR { get; set; }
        [InverseProperty("TL_LOGICIEL")]
        public virtual ICollection<TEL_ETAT_LOGICIELS> TEL_ETAT_LOGICIELS { get; set; }
        [InverseProperty("TL_LOGICIEL")]
        public virtual ICollection<TSL_SERVEUR_LOGICIELS> TSL_SERVEUR_LOGICIELS { get; set; }
    }
}