// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    public partial class TLEM_LOGICIEL_EDITEUR_MODELES
    {
        [Display(Name = "Display_TLEM_LOGICIEL_EDITEUR_MODELES_TLEM_LOGICIEL_EDITEUR_MODELEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Key]
        public int TLEM_LOGICIEL_EDITEUR_MODELEID { get; set; }

        [Display(Name = "Display_TLEM_LOGICIEL_EDITEUR_MODELES_TLE_LOGICIEL_EDITEURID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TLE_LOGICIEL_EDITEURID { get; set; }

        [Display(Name = "Display_TLEM_LOGICIEL_EDITEUR_MODELES_TLEM_ACTION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        [StringLength(3)]
        public string TLEM_ACTION { get; set; }

        [Display(Name = "Display_TLEM_LOGICIEL_EDITEUR_MODELES_TLEM_FILE_TYPE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        [StringLength(1)]
        public string TLEM_FILE_TYPE { get; set; }

        [Display(Name = "Display_TLEM_LOGICIEL_EDITEUR_MODELES_TLEM_PATH_NAME", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(250)]
        public string TLEM_PATH_NAME { get; set; }

        [Display(Name = "Display_TLEM_LOGICIEL_EDITEUR_MODELES_TLEM_FILENAME_PATTERN", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(250)]
        public string TLEM_FILENAME_PATTERN { get; set; }

        [Display(Name = "Display_TLEM_LOGICIEL_EDITEUR_MODELES_TLEM_INFO", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(30)]
        public string TLEM_INFO { get; set; }

        [ForeignKey(nameof(TLE_LOGICIEL_EDITEURID))]
        [InverseProperty(nameof(TLE_LOGICIEL_EDITEURS.TLEM_LOGICIEL_EDITEUR_MODELES))]
        public virtual TLE_LOGICIEL_EDITEURS TLE_LOGICIEL_EDITEUR { get; set; }
    }
}