// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    public partial class TP_PERIMETRES
    {
        public TP_PERIMETRES()
        {
         
            TEM_ETAT_MASTERS = new HashSet<TEM_ETAT_MASTERS>();
        }

        [Key]
        public int TP_PERIMETREID { get; set; }
        [StringLength(255)]
        public string TP_PERIMETRE { get; set; }
        
        [DisplayFormat(DataFormatString = "g")]
        public DateTime? TP_DATE_CREATION { get; set; }
        [Required]
        [StringLength(3)]
        public string TRST_STATUTID { get; set; }
        public byte[] TP_LOGO { get; set; }
        public int? TQM_QUALIF_MODELEID { get; set; }

        [ForeignKey(nameof(TQM_QUALIF_MODELEID))]
        [InverseProperty(nameof(TQM_QUALIF_MODELES.TP_PERIMETRES))]
        public virtual TQM_QUALIF_MODELES TQM_QUALIF_MODELE { get; set; }
        [ForeignKey(nameof(TRST_STATUTID))]
        [InverseProperty(nameof(TRST_STATUTS.TP_PERIMETRES))]
        public virtual TRST_STATUTS TRST_STATUT { get; set; }
        
        [InverseProperty("TP_PERIMETRE")]
        public virtual ICollection<TEM_ETAT_MASTERS> TEM_ETAT_MASTERS { get; set; }
    }
}