// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    public partial class TPF_PLANIFS
    {
        [Key]
        public int TPF_PLANIFID { get; set; }

        [DisplayFormat(DataFormatString = "g")]
        [Display(Name = "Display_TPF_PLANIFS_TPF_DATE_DEBUT", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public DateTime TPF_DATE_DEBUT { get; set; }

        [DisplayFormat(DataFormatString = "g")]
        [Display(Name = "Display_TPF_PLANIFS_TPF_DATE_FIN", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public DateTime? TPF_DATE_FIN { get; set; }

        [Required]
        [StringLength(3)]
        [Display(Name = "Display_TPF_PLANIFS_TRST_STATUTID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRST_STATUTID { get; set; }

        [Display(Name = "Display_TPF_PLANIFS_TPF_DEMANDE_ORIGINEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TPF_DEMANDE_ORIGINEID { get; set; }

        [Display(Name = "Display_TPF_PLANIFS_TPF_PREREQUIS_DELAI_CHK", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TPF_PREREQUIS_DELAI_CHK { get; set; }

        [StringLength(255)]
        [Display(Name = "Display_TPF_PLANIFS_TPF_CRON", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TPF_CRON { get; set; }
        
        [StringLength(255)]
        [Required]
        [Display(Name = "Display_TPF_PLANIFS_TPF_TIMEZONE_INFOID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TPF_TIMEZONE_INFOID { get; set; }

        [StringLength(36)]
        [Display(Name = "Display_TPF_PLANIFS_TRU_DECLARANTID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRU_DECLARANTID { get; set; }

        [ForeignKey(nameof(TPF_DEMANDE_ORIGINEID))]
        [InverseProperty(nameof(TD_DEMANDES.TPF_PLANIFS))]
        public virtual TD_DEMANDES TPF_DEMANDE_ORIGINE { get; set; }
        [ForeignKey(nameof(TRST_STATUTID))]
        [InverseProperty(nameof(TRST_STATUTS.TPF_PLANIFS))]
        public virtual TRST_STATUTS TRST_STATUT { get; set; }
    }
}