// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    [DisplayColumn("TPR_LIB")]
    public partial class TPR_PROFILS
    {
        [Key]
        public int TPR_PROFILID { get; set; }
        [Required]
        [StringLength(255)]
        public string TPR_LIB { get; set; }
        [Required]
        [StringLength(3)]
        public string TRST_STATUTID { get; set; }

        [ForeignKey(nameof(TRST_STATUTID))]
        [InverseProperty(nameof(TRST_STATUTS.TPR_PROFILS))]
        public virtual TRST_STATUTS TRST_STATUT { get; set; }
    }
}