// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    public partial class TPS_PREREQUIS_SCENARIOS
    {
        [Key]
        public int TEP_ETAT_PREREQUISID { get; set; }
        [Key]
        public int TS_SCENARIOID { get; set; }
        public int? TPS_NB_FILE_MIN { get; set; }
        public int? TPS_NB_FILE_MAX { get; set; }
        [StringLength(255)]
        public string TPS_COMMENTAIRE { get; set; }

        [ForeignKey(nameof(TEP_ETAT_PREREQUISID))]
        [InverseProperty(nameof(TEP_ETAT_PREREQUISS.TPS_PREREQUIS_SCENARIOS))]
        public virtual TEP_ETAT_PREREQUISS TEP_ETAT_PREREQUIS { get; set; }
        [ForeignKey(nameof(TS_SCENARIOID))]
        [InverseProperty(nameof(TS_SCENARIOS.TPS_PREREQUIS_SCENARIOS))]
        public virtual TS_SCENARIOS TS_SCENARIO { get; set; }
    }
}