// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    [Index(nameof(TPU_INSTANCE), nameof(TSRV_SERVEURID), Name = "UQ_TPU_PARALLELEUS", IsUnique = true)]

    [DisplayColumn("TPU_INSTANCE")]
    public partial class TPU_PARALLELEUS
    {
        public TPU_PARALLELEUS()
        {
            TPUF_PARALLELEU_FERMES = new HashSet<TPUF_PARALLELEU_FERMES>();
            TPUP_PARALLELEU_PARAMS = new HashSet<TPUP_PARALLELEU_PARAMS>();
        }

        [Display(Name = "Display_TPU_PARALLELEUS_TPU_PARALLELEUID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Key]
        public int TPU_PARALLELEUID { get; set; }

        [Display(Name = "Display_TPU_PARALLELEUS_TPU_INSTANCE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        [StringLength(255)]
        public string TPU_INSTANCE { get; set; }

        [Display(Name = "Display_TPU_PARALLELEUS_TRST_STATUTID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        [StringLength(3)]
        public string TRST_STATUTID { get; set; }

        [Display(Name = "Display_TPU_PARALLELEUS_TPU_DATE_PREMIERE_ACTIVITE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [DisplayFormat(DataFormatString = "g")] 
        public DateTime? TPU_DATE_PREMIERE_ACTIVITE { get; set; }

        [Display(Name = "Display_TPU_PARALLELEUS_TPU_DATE_DERNIERE_ACTIVITE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [DisplayFormat(DataFormatString = "g")]
        public DateTime? TPU_DATE_DERNIERE_ACTIVITE { get; set; }

        [Display(Name = "Display_TPU_PARALLELEUS_TPU_DUREE_EXPLOITATION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TPU_DUREE_EXPLOITATION { get; set; }

        [Display(Name = "Display_TPU_PARALLELEUS_TPU_DESCR", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(255)]
        public string TPU_DESCR { get; set; }

        [Display(Name = "Display_TPU_PARALLELEUS_TSRV_SERVEURID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TSRV_SERVEURID { get; set; }

        [ForeignKey(nameof(TRST_STATUTID))]
        [InverseProperty(nameof(TRST_STATUTS.TPU_PARALLELEUS))]
        public virtual TRST_STATUTS TRST_STATUT { get; set; }
        [ForeignKey(nameof(TSRV_SERVEURID))]
        [InverseProperty(nameof(TSRV_SERVEURS.TPU_PARALLELEUS))]
        public virtual TSRV_SERVEURS TSRV_SERVEUR { get; set; }
        [InverseProperty("TPU_PARALLELEU")]
        public virtual ICollection<TPUF_PARALLELEU_FERMES> TPUF_PARALLELEU_FERMES { get; set; }
        [InverseProperty("TPU_PARALLELEU")]
        public virtual ICollection<TPUP_PARALLELEU_PARAMS> TPUP_PARALLELEU_PARAMS { get; set; }
    }
}