// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    public partial class TPUF_PARALLELEU_FERMES
    {
        [Display(Name = "Display_TPUF_PARALLELEU_FERMES_TPUF_PARALLELEU_FERMEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Key]
        public int TPUF_PARALLELEU_FERMEID { get; set; }
        
        [Display(Name = "Display_TPUF_PARALLELEU_FERMES_TF_FERMEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TF_FERMEID { get; set; }

        [Display(Name = "Display_TPUF_PARALLELEU_FERMES_TPU_PARALLELEUID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TPU_PARALLELEUID { get; set; }

        [Display(Name = "Display_TPUF_PARALLELEU_FERMES_TRST_STATUTID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        [StringLength(3)]
        public string TRST_STATUTID { get; set; }

        [Display(Name = "Display_TPUF_PARALLELEU_FERMES_TPUF_DATE_MODIFICATION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [DisplayFormat(DataFormatString = "g")]
        public DateTime? TPUF_DATE_MODIFICATION { get; set; }

        [Display(Name = "Display_TPUF_PARALLELEU_FERMES_TPUF_DESCR", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(255)]
        public string TPUF_DESCR { get; set; }


        [ForeignKey(nameof(TF_FERMEID))]
        [InverseProperty(nameof(TF_FERMES.TPUF_PARALLELEU_FERMES))]
        public virtual TF_FERMES TF_FERME { get; set; }
        [ForeignKey(nameof(TPU_PARALLELEUID))]
        [InverseProperty(nameof(TPU_PARALLELEUS.TPUF_PARALLELEU_FERMES))]
        public virtual TPU_PARALLELEUS TPU_PARALLELEU { get; set; }
        [ForeignKey(nameof(TRST_STATUTID))]
        [InverseProperty(nameof(TRST_STATUTS.TPUF_PARALLELEU_FERMES))]
        public virtual TRST_STATUTS TRST_STATUT { get; set; }
    }
}