// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    [Index(nameof(TPU_PARALLELEUID), nameof(TPUP_KEY), Name = "UQ_PARALLELEU_PARAM", IsUnique = true)]
    public partial class TPUP_PARALLELEU_PARAMS
    {
        [Display(Name = "Display_TPUP_PARALLELEU_PARAMS_TPUP_PARALLELEU_PARAMID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Key]
        public int TPUP_PARALLELEU_PARAMID { get; set; }

        [Display(Name = "Display_TPUP_PARALLELEU_PARAMS_TPU_PARALLELEUID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TPU_PARALLELEUID { get; set; }

        [Display(Name = "Display_TPUP_PARALLELEU_PARAMS_TPUP_KEY", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        [StringLength(255)]
        public string TPUP_KEY { get; set; }

        [Display(Name = "Display_TPUP_PARALLELEU_PARAMS_TPUP_VALUE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        [StringLength(255)]
        public string TPUP_VALUE { get; set; }

        [Display(Name = "Display_TPUP_PARALLELEU_PARAMS_TPUP_TYPE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(255)]
        public string TPUP_TYPE { get; set; }

        [Display(Name = "Display_TPUP_PARALLELEU_PARAMS_TRST_STATUTID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        [StringLength(3)]
        public string TRST_STATUTID { get; set; }

        [Display(Name = "Display_TPUP_PARALLELEU_PARAMS_TPUP_DESCR", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(255)]
        public string TPUP_DESCR { get; set; }

        [ForeignKey(nameof(TPU_PARALLELEUID))]
        [InverseProperty(nameof(TPU_PARALLELEUS.TPUP_PARALLELEU_PARAMS))]
        public virtual TPU_PARALLELEUS TPU_PARALLELEU { get; set; }
        [ForeignKey(nameof(TRST_STATUTID))]
        [InverseProperty(nameof(TRST_STATUTS.TPUP_PARALLELEU_PARAMS))]
        public virtual TRST_STATUTS TRST_STATUT { get; set; }
    }
}