// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    public partial class TQM_QUALIF_MODELES
    {
        public TQM_QUALIF_MODELES()
        {
            TP_PERIMETRES = new HashSet<TP_PERIMETRES>();
        }

        [Key]
        public int TQM_QUALIF_MODELEID { get; set; }
        [Required]
        [StringLength(30)]
        public string TQM_LIB { get; set; }
        public int? TQM_VALEUR_MIN { get; set; }
        public int? TQM_VALEUR_MAX { get; set; }

        [InverseProperty("TQM_QUALIF_MODELE")]
        public virtual ICollection<TP_PERIMETRES> TP_PERIMETRES { get; set; }
    }
}