// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    [Index(nameof(TER_ETAT_RESSOURCEID), Name = "IX_TRS_RESSOURCE_SCENARIOS$ETAT_RESSOURCE")]
    [Index(nameof(TS_SCENARIOID), Name = "IX_TRS_RESSOURCE_SCENARIOS$TS_SCENARIOS")]
    public partial class TRS_RESSOURCE_SCENARIOS
    {
        [Key]
        public int TER_ETAT_RESSOURCEID { get; set; }
        [Key]
        public int TS_SCENARIOID { get; set; }

        [Required]
        [StringLength(1)]
        public string TRS_FICHIER_OBLIGATOIRE { get; set; }
        [StringLength(255)]
        public string TRS_COMMENTAIRE { get; set; }

        [ForeignKey(nameof(TER_ETAT_RESSOURCEID))]
        [InverseProperty(nameof(TER_ETAT_RESSOURCES.TRS_RESSOURCE_SCENARIOS))]
        public virtual TER_ETAT_RESSOURCES TER_ETAT_RESSOURCE { get; set; }
        [ForeignKey(nameof(TS_SCENARIOID))]
        [InverseProperty(nameof(TS_SCENARIOS.TRS_RESSOURCE_SCENARIOS))]
        public virtual TS_SCENARIOS TS_SCENARIO { get; set; }
    }
}