// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    [DisplayColumn("TS_NOM_SCENARIO")]
    public partial class TS_SCENARIOS
    {

        public TS_SCENARIOS()
        {
            TBS_BATCH_SCENARIOS = new HashSet<TBS_BATCH_SCENARIOS>();
            TPS_PREREQUIS_SCENARIOS = new HashSet<TPS_PREREQUIS_SCENARIOS>();
            TRS_RESSOURCE_SCENARIOS = new HashSet<TRS_RESSOURCE_SCENARIOS>();
            VDE_DEMANDES_ETENDUE = new HashSet<VDE_DEMANDES_ETENDUES>();

            TH_HABILITATION = new HashSet<TH_HABILITATIONS>();

            VDTFH_HABILITATION = new HashSet<VDTFH_HABILITATIONS>();

            TSGA_SCENARIO_GPE_ASSOCIE = new HashSet<TSGA_SCENARIO_GPE_ASSOCIES>();

            VPE_PLANIF_ENTETE = new HashSet<VPE_PLANIF_ENTETES>();

            TCMD_COMMANDES_TS_SCENARIO = new HashSet<TCMD_COMMANDES>();

        }

        [Display(Name = "Display_TS_SCENARIOS_TS_SCENARIOID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Key]
        public int TS_SCENARIOID { get; set; }

        [Required]
        [StringLength(255)]
        [Display(Name = "Display_TS_SCENARIOS_TS_NOM_SCENARIO", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TS_NOM_SCENARIO { get; set; }


        [StringLength(255)]
        [Display(Name = "Display_TS_SCENARIOS_TS_DESCR", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TS_DESCR { get; set; }

        [Required]
        [StringLength(1)]
        [Display(Name = "Display_TS_SCENARIOS_TRST_STATUTID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRST_STATUTID { get; set; }

        [StringLength(1)]
        [Display(Name = "Display_TS_SCENARIOS_TRST_STATUTID_OLD", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRST_STATUTID_OLD { get; set; }

        [Display(Name = "Display_TS_SCENARIOS_TE_ETATID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TE_ETATID { get; set; }
        
        [StringLength(1)]
        [Display(Name = "Display_TS_SCENARIOS_TS_IS_DEFAULT", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TS_IS_DEFAULT { get; set; }


        [StringLength(36)]
        [Display(Name = "Display_TS_SCENARIOS_TS_GUID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TS_GUID { get; set; }

        /* FK */
        [ForeignKey(nameof(TE_ETATID))]
        [InverseProperty(nameof(TE_ETATS.TS_SCENARIOS))]
        public virtual TE_ETATS TE_ETAT { get; set; }

        [ForeignKey(nameof(TRST_STATUTID))]
        [InverseProperty(nameof(TRST_STATUTS.TS_SCENARIOS))]
        public virtual TRST_STATUTS TRST_STATUT { get; set; }

        /* ENFANT */
        [InverseProperty("TS_SCENARIO")]
        public virtual ICollection<TBS_BATCH_SCENARIOS> TBS_BATCH_SCENARIOS { get; set; }

        [InverseProperty("TS_SCENARIO")]
        public virtual ICollection<TPS_PREREQUIS_SCENARIOS> TPS_PREREQUIS_SCENARIOS { get; set; }
       
        [InverseProperty("TS_SCENARIO")]
        public virtual ICollection<TRS_RESSOURCE_SCENARIOS> TRS_RESSOURCE_SCENARIOS { get; set; }
         
        
        [InverseProperty(nameof(VDE_DEMANDES_ETENDUES.TS_SCENARIO))]
        public virtual ICollection<VDE_DEMANDES_ETENDUES> VDE_DEMANDES_ETENDUE { get; set; }


        [InverseProperty(nameof(VDTFH_HABILITATIONS.TS_SCENARIO))]
        public virtual ICollection<VDTFH_HABILITATIONS> VDTFH_HABILITATION { get; set; }


        [InverseProperty(nameof(TH_HABILITATIONS.TS_SCENARIO))]
        public virtual ICollection<TH_HABILITATIONS> TH_HABILITATION { get; set; }

        [InverseProperty(nameof(TSGA_SCENARIO_GPE_ASSOCIES.TS_SCENARIO))]
        public virtual ICollection<TSGA_SCENARIO_GPE_ASSOCIES> TSGA_SCENARIO_GPE_ASSOCIE { get; set; }


        [InverseProperty(nameof(VPE_PLANIF_ENTETES.TS_SCENARIO))]
        public virtual ICollection<VPE_PLANIF_ENTETES> VPE_PLANIF_ENTETE { get; set; }

        [InverseProperty(nameof(TCMD_COMMANDES.TS_SCENARIO))]
        public virtual ICollection<TCMD_COMMANDES> TCMD_COMMANDES_TS_SCENARIO { get; set; }


    }
}