// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    [Index(nameof(TSRV_SERVEURID), nameof(TL_LOGICIELID), Name = "UQ_SERVEUR_LOGICIEL", IsUnique = true)]
    public partial class TSL_SERVEUR_LOGICIELS
    {
        [Display(Name = "Display_TSL_SERVEUR_LOGICIELS_TSL_SERVEUR_LOGICIELID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Key]
        public int TSL_SERVEUR_LOGICIELID { get; set; }

        [Display(Name = "Display_TSL_SERVEUR_LOGICIELS_TSRV_SERVEURID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TSRV_SERVEURID { get; set; }

        [Display(Name = "Display_TSL_SERVEUR_LOGICIELS_TL_LOGICIELID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TL_LOGICIELID { get; set; }

        [ForeignKey(nameof(TL_LOGICIELID))]
        [InverseProperty(nameof(TL_LOGICIELS.TSL_SERVEUR_LOGICIELS))]
        public virtual TL_LOGICIELS TL_LOGICIEL { get; set; }
        [ForeignKey(nameof(TSRV_SERVEURID))]
        [InverseProperty(nameof(TSRV_SERVEURS.TSL_SERVEUR_LOGICIELS))]
        public virtual TSRV_SERVEURS TSRV_SERVEUR { get; set; }
    }
}