// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    [Index(nameof(TSRV_NOM), Name = "UQ_TSRV_SERVEURS$TSRV_NOM", IsUnique = true)]

    [DisplayColumn("TSRV_NOM")]

    public partial class TSRV_SERVEURS
    {
        public TSRV_SERVEURS()
        {
            TD_DEMANDES = new HashSet<TD_DEMANDES>();
            TPU_PARALLELEUS = new HashSet<TPU_PARALLELEUS>();
            TSL_SERVEUR_LOGICIELS = new HashSet<TSL_SERVEUR_LOGICIELS>();
            TSP_SERVEUR_PARAMS = new HashSet<TSP_SERVEUR_PARAMS>();
        }

        [Display(Name = "Display_TSRV_SERVEURS_TSRV_SERVEURID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Key]
        public int TSRV_SERVEURID { get; set; }

        [Display(Name = "Display_TSRV_SERVEURS_TSRV_NOM", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        [StringLength(255)]
        public string TSRV_NOM { get; set; }

        [Display(Name = "Display_TSRV_SERVEURS_TSRV_IP", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(15)]
        public string TSRV_IP { get; set; }

        [Display(Name = "Display_TSRV_SERVEURS_TSRV_DATE_ACTIVATION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [DisplayFormat(DataFormatString = "g")]
        public DateTime? TSRV_DATE_ACTIVATION { get; set; }

        [Display(Name = "Display_TSRV_SERVEURS_TSRV_DATE_DERNIERE_ACTIVITE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [DisplayFormat(DataFormatString = "g")]
        public DateTime? TSRV_DATE_DERNIERE_ACTIVITE { get; set; }

        [Display(Name = "Display_TSRV_SERVEURS_TSRV_DUREE_EXPLOITATION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TSRV_DUREE_EXPLOITATION { get; set; }

        [Display(Name = "Display_TSRV_SERVEURS_TRST_STATUTID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        [StringLength(3)]
        public string TRST_STATUTID { get; set; }

        [Display(Name = "Display_TSRV_SERVEURS_TSRV_OS", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(255)]
        public string TSRV_OS { get; set; }

        [Display(Name = "Display_TSRV_SERVEURS_TSRV_DESCR", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [StringLength(255)]
        public string TSRV_DESCR { get; set; }

        [ForeignKey(nameof(TRST_STATUTID))]
        [InverseProperty(nameof(TRST_STATUTS.TSRV_SERVEURS))]
        public virtual TRST_STATUTS TRST_STATUT { get; set; }
        [InverseProperty("TSRV_SERVEUR")]
        public virtual ICollection<TD_DEMANDES> TD_DEMANDES { get; set; }
        [InverseProperty("TSRV_SERVEUR")]
        public virtual ICollection<TPU_PARALLELEUS> TPU_PARALLELEUS { get; set; }
        [InverseProperty("TSRV_SERVEUR")]
        public virtual ICollection<TSL_SERVEUR_LOGICIELS> TSL_SERVEUR_LOGICIELS { get; set; }
        [InverseProperty("TSRV_SERVEUR")]
        public virtual ICollection<TSP_SERVEUR_PARAMS> TSP_SERVEUR_PARAMS { get; set; }
    }
}