// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    public partial class TCMD_RP_RAISON_PHASES
    {
        public TCMD_RP_RAISON_PHASES()
        {
            TCMD_CR_CMD_RAISON_PHASES = new HashSet<TCMD_CR_CMD_RAISON_PHASES>();
        }

        [Key]
        [Display(Name = "Display_TCMD_RP_RAISON_PHASES_TCMD_RP_RAISON_PHASEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TCMD_RP_RAISON_PHASEID { get; set; }

        [Display(Name = "Display_TCMD_RP_RAISON_PHASES_TCMD_RP_LIB_FR", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        public string TCMD_RP_LIB_FR { get; set; }

        [Display(Name = "Display_TCMD_RP_RAISON_PHASES_TCMD_RP_LIB_EN", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        public string TCMD_RP_LIB_EN { get; set; }

        [Display(Name = "Display_TCMD_RP_RAISON_PHASES_TCMD_PH_PHASEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TCMD_PH_PHASEID { get; set; }

        [ForeignKey("TCMD_PH_PHASEID")]
        [InverseProperty("TCMD_RP_RAISON_PHASES")]
        public virtual TCMD_PH_PHASES TCMD_PH_PHASE { get; set; }
        [InverseProperty("TCMD_RP_RAISON_PHASE")]
        public virtual ICollection<TCMD_CR_CMD_RAISON_PHASES> TCMD_CR_CMD_RAISON_PHASES { get; set; }
    }
}