// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    [Index("TCMD_COMMANDEID", "TCMD_DOC_FILENAME", Name = "IX_TCMD_DOC_DOCUMENTS", IsUnique = true)]
    public partial class TCMD_DOC_DOCUMENTS
    {
        [Key]
        [Display(Name = "Display_TCMD_DOC_DOCUMENTS_TCMD_DOC_DOCUMENTID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TCMD_DOC_DOCUMENTID { get; set; }

        [Display(Name = "Display_TCMD_DOC_DOCUMENTS_TCMD_DOC_FILENAME", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        public string TCMD_DOC_FILENAME { get; set; }
		
		//[DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "g")]
        [Required]
        [Display(Name = "Display_TCMD_DOC_DOCUMENTS_TCMD_DOC_DATE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public DateTime TCMD_DOC_DATE { get; set; }

        [Display(Name = "Display_TCMD_DOC_DOCUMENTS_TCMD_DOC_COMMENTAIRE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        public string TCMD_DOC_COMMENTAIRE { get; set; }

        [Display(Name = "Display_TCMD_DOC_DOCUMENTS_TCMD_COMMANDEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TCMD_COMMANDEID { get; set; }

        [Display(Name = "Display_TCMD_DOC_DOCUMENTS_TCMD_TD_TYPE_DOCUMENTID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TCMD_TD_TYPE_DOCUMENTID { get; set; }

        [Display(Name = "Display_TCMD_DOC_DOCUMENTS_TCMD_DOC_TAILLE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TCMD_DOC_TAILLE { get; set; }

        [ForeignKey("TCMD_COMMANDEID")]
        [InverseProperty("TCMD_DOC_DOCUMENTS")]
        public virtual TCMD_COMMANDES TCMD_COMMANDE { get; set; }
        [ForeignKey("TCMD_TD_TYPE_DOCUMENTID")]
        [InverseProperty("TCMD_DOC_DOCUMENTS")]
        public virtual TCMD_TD_TYPE_DOCUMENTS TCMD_TD_TYPE_DOCUMENT { get; set; }
    }
}