// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{

    [DisplayColumn("TCMD_PH_CODE")]

    public partial class TCMD_PH_PHASES
    {
        public TCMD_PH_PHASES()
        {
            TCMD_COMMANDES = new HashSet<TCMD_COMMANDES>();
            TCMD_RP_RAISON_PHASES = new HashSet<TCMD_RP_RAISON_PHASES>();
            TCMD_SP_SUIVI_PHASESTCMD_PH_PHASE_APRES = new HashSet<TCMD_SP_SUIVI_PHASES>();
            TCMD_SP_SUIVI_PHASESTCMD_PH_PHASE_AVANT = new HashSet<TCMD_SP_SUIVI_PHASES>();
        }

        [Key]
        [Display(Name = "Display_TCMD_PH_PHASES_TCMD_PH_PHASEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TCMD_PH_PHASEID { get; set; }

        [Display(Name = "Display_TCMD_PH_PHASES_TCMD_PH_CODE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        public string TCMD_PH_CODE { get; set; }

        [Display(Name = "Display_TCMD_PH_PHASES_TCMD_PH_LIB_FR", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        public string TCMD_PH_LIB_FR { get; set; }


        [Display(Name = "Display_TCMD_PH_PHASES_TCMD_PH_LIB_EN", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        public string TCMD_PH_LIB_EN { get; set; }

        [Display(Name = "Display_TCMD_PH_PHASES_TCMD_PH_DELAI_RECYCLAGE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TCMD_PH_DELAI_RECYCLAGE { get; set; }

        [InverseProperty("TCMD_PH_PHASE")]
        public virtual ICollection<TCMD_COMMANDES> TCMD_COMMANDES { get; set; }
        [InverseProperty("TCMD_PH_PHASE")]
        public virtual ICollection<TCMD_RP_RAISON_PHASES> TCMD_RP_RAISON_PHASES { get; set; }
        [InverseProperty("TCMD_PH_PHASE_APRES")]
        public virtual ICollection<TCMD_SP_SUIVI_PHASES> TCMD_SP_SUIVI_PHASESTCMD_PH_PHASE_APRES { get; set; }
        [InverseProperty("TCMD_PH_PHASE_AVANT")]
        public virtual ICollection<TCMD_SP_SUIVI_PHASES> TCMD_SP_SUIVI_PHASESTCMD_PH_PHASE_AVANT { get; set; }
    }

    /// <summary>
    /// Order phases.
    /// </summary>
    public static class Phases
    {
        /// <summary>
        /// Draft phase code.
        /// </summary>
        public const string Draft = "BR";
        /// <summary>
        /// "To accept" phase code.
        /// </summary>
        public const string ToAccept = "AA";
        /// <summary>
        /// "In progress" phase code.
        /// </summary>
        public const string InProgress = "EC";
        /// <summary>
        /// Rejected phase code.
        /// </summary>
        public const string Rejected = "RJ";
        /// <summary>
        /// Frost phase code.
        /// </summary>
        public const string Frost = "GL";
        /// <summary>
        /// Delivered phase code.
        /// </summary>
        public const string Delivered = "LI";
        /// <summary>
        /// Completed phase code.
        /// </summary>
        public const string Completed = "TE";
        /// <summary>
        /// Canceled phase code.
        /// </summary>
        public const string Canceled = "AN";
        /// <summary>
        /// Archived phase code.
        /// </summary>
        public const string Archived = "AR";
    }
}