// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    public partial class TCMD_SP_SUIVI_PHASES
    {
        public TCMD_SP_SUIVI_PHASES()
        {
            TCMD_CR_CMD_RAISON_PHASES = new HashSet<TCMD_CR_CMD_RAISON_PHASES>();
        }

        [Key]
        [Display(Name = "Display_TCMD_SP_SUIVI_PHASES_TCMD_SP_SUIVI_PHASEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TCMD_SP_SUIVI_PHASEID { get; set; }

        [Display(Name = "Display_TCMD_SP_SUIVI_PHASES_TCMD_COMMANDEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TCMD_COMMANDEID { get; set; }
		
		//[DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "g")]
        [Display(Name = "Display_TCMD_SP_SUIVI_PHASES_TCMD_SP_DATE_MODIF", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public DateTime? TCMD_SP_DATE_MODIF { get; set; }

        [Display(Name = "Display_TCMD_SP_SUIVI_PHASES_TRU_AUTEUR_MODIFID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRU_AUTEUR_MODIFID { get; set; }

        [Display(Name = "Display_TCMD_SP_SUIVI_PHASES_TCMD_SP_COMMENTAIRE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TCMD_SP_COMMENTAIRE { get; set; }

        [Display(Name = "Display_TCMD_SP_SUIVI_PHASES_TCMD_PH_PHASE_AVANTID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TCMD_PH_PHASE_AVANTID { get; set; }

        [Display(Name = "Display_TCMD_SP_SUIVI_PHASES_TCMD_PH_PHASE_APRESID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TCMD_PH_PHASE_APRESID { get; set; }

        [ForeignKey("TCMD_COMMANDEID")]
        [InverseProperty("TCMD_SP_SUIVI_PHASES")]
        public virtual TCMD_COMMANDES TCMD_COMMANDE { get; set; }
        [ForeignKey("TCMD_PH_PHASE_APRESID")]
        [InverseProperty("TCMD_SP_SUIVI_PHASESTCMD_PH_PHASE_APRES")]
        public virtual TCMD_PH_PHASES TCMD_PH_PHASE_APRES { get; set; }
       
        [ForeignKey("TCMD_PH_PHASE_AVANTID")]
        [InverseProperty("TCMD_SP_SUIVI_PHASESTCMD_PH_PHASE_AVANT")]
        public virtual TCMD_PH_PHASES TCMD_PH_PHASE_AVANT { get; set; }

        [ForeignKey(nameof(TRU_AUTEUR_MODIFID))]
        [InverseProperty(nameof(TRU_USERS.TCMD_SP_SUIVI_PHASES_TRU_AUTEUR_MODIF))]
        public virtual TRU_USERS TRU_AUTEUR_MODIF { get; set; }


        //enfant
        [InverseProperty("TCMD_SP_SUIVI_PHASE")]
        public virtual ICollection<TCMD_CR_CMD_RAISON_PHASES> TCMD_CR_CMD_RAISON_PHASES { get; set; }

      

    }
}