// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{

    [DisplayColumn("TCMD_TD_TYPE")]

    [Index("TCMD_TD_TYPE", Name = "IX_TCMD_TD_TYPE_DOCUMENTS", IsUnique = true)]
    public partial class TCMD_TD_TYPE_DOCUMENTS
    {
        public TCMD_TD_TYPE_DOCUMENTS()
        {
            TCMD_DOC_DOCUMENTS = new HashSet<TCMD_DOC_DOCUMENTS>();
        }

        [Key]
        [Display(Name = "Display_TCMD_TD_TYPE_DOCUMENTS_TCMD_TD_TYPE_DOCUMENTID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TCMD_TD_TYPE_DOCUMENTID { get; set; }


        [Display(Name = "Display_TCMD_TD_TYPE_DOCUMENTS_TCMD_TD_TYPE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        public string TCMD_TD_TYPE { get; set; }

        [Display(Name = "Display_TCMD_TD_TYPE_DOCUMENTS_TCMD_TD_COMMENTAIRE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        public string TCMD_TD_COMMENTAIRE { get; set; }

        [InverseProperty("TCMD_TD_TYPE_DOCUMENT")]
        public virtual ICollection<TCMD_DOC_DOCUMENTS> TCMD_DOC_DOCUMENTS { get; set; }
    }
}