// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    public partial class TCMD_DA_DEMANDES_ASSOCIEES
    {
        [Key]
        [Display(Name = "Display_TCMD_DA_DEMANDES_ASSOCIEES_TCMD_DA_DEMANDES_ASSOCIEEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TCMD_DA_DEMANDES_ASSOCIEEID { get; set; }

        [Display(Name = "Display_TCMD_DA_DEMANDES_ASSOCIEES_TCMD_COMMANDEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TCMD_COMMANDEID { get; set; }

        [Display(Name = "Display_TCMD_DA_DEMANDES_ASSOCIEES_TD_DEMANDEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TD_DEMANDEID { get; set; }

        [Display(Name = "Display_TCMD_DA_DEMANDES_ASSOCIEES_TCMD_DA_COMMENTAIRE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TCMD_DA_COMMENTAIRE { get; set; }

        [Display(Name = "Display_TCMD_DA_DEMANDES_ASSOCIEES_TCMD_DA_VERSION_NOTABLE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TCMD_DA_VERSION_NOTABLE { get; set; }

        //[DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "g")]
        [Required]
        [Display(Name = "Display_TCMD_DA_DEMANDES_ASSOCIEES_TCMD_DA_DATE_ASSOCIATION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public DateTime TCMD_DA_DATE_ASSOCIATION { get; set; }


        [Display(Name = "Display_TCMD_DA_DEMANDES_ASSOCIEES_TRU_AUTEURID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRU_AUTEURID { get; set; }

        [ForeignKey("TCMD_COMMANDEID")]
        [InverseProperty("TCMD_DA_DEMANDES_ASSOCIEES")]
        public virtual TCMD_COMMANDES TCMD_COMMANDE { get; set; }


        [ForeignKey(nameof( TRU_AUTEURID))]
        [InverseProperty(nameof(TRU_USERS.TCMD_DA_DEMANDES_ASSOCIEES_TRU_AUTEUR))]
        public virtual TRU_USERS TRU_AUTEUR { get; set; }

        [ForeignKey(nameof(TD_DEMANDEID))]
        [InverseProperty(nameof(TD_DEMANDES.TCMD_DA_DEMANDES_ASSOCIEES_TD_DEMANDE))]
        public virtual TD_DEMANDES TD_DEMANDE { get; set; }

    }
}