// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{

    [DisplayColumn("TCMD_COMMANDEID")]

    public partial class TCMD_COMMANDES
    {
        public TCMD_COMMANDES()
        {
            InverseTCMD_ORIGINE = new HashSet<TCMD_COMMANDES>();
            TCMD_DA_DEMANDES_ASSOCIEES = new HashSet<TCMD_DA_DEMANDES_ASSOCIEES>();
            TCMD_DOC_DOCUMENTS = new HashSet<TCMD_DOC_DOCUMENTS>();
            TCMD_SP_SUIVI_PHASES = new HashSet<TCMD_SP_SUIVI_PHASES>();
            TDC_DEMANDES_COMMANDES = new HashSet<TDC_DEMANDES_COMMANDES>();
        }

        [Key]
        [Display(Name = "Display_TCMD_COMMANDES_TCMD_COMMANDEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TCMD_COMMANDEID { get; set; }
        
        [Required]
       // [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "g")]
        [Display(Name = "Display_TCMD_COMMANDES_TCMD_DATE_CREATION", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public DateTime TCMD_DATE_CREATION { get; set; }

       // [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "g")]
        [Display(Name = "Display_TCMD_COMMANDES_TCMD_DATE_PASSAGE_CMD", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public DateTime? TCMD_DATE_PASSAGE_CMD { get; set; }

       // [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "g")]
        [Display(Name = "Display_TCMD_COMMANDES_TCMD_DATE_LIVRAISON_SOUHAITEE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public DateTime? TCMD_DATE_LIVRAISON_SOUHAITEE { get; set; }

       // [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "g")]
        [Display(Name = "Display_TCMD_COMMANDES_TCMD_DATE_MODIF", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        public DateTime TCMD_DATE_MODIF { get; set; }

       // [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "g")]
        [Display(Name = "Display_TCMD_COMMANDES_TCMD_DATE_PRISE_EN_CHARGE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public DateTime? TCMD_DATE_PRISE_EN_CHARGE { get; set; }

       // [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "g")]
        [Display(Name = "Display_TCMD_COMMANDES_TCMD_DATE_PREVISIONNELLE_LIVRAISON", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public DateTime? TCMD_DATE_PREVISIONNELLE_LIVRAISON { get; set; }

        //[DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "g")]
        [Display(Name = "Display_TCMD_COMMANDES_TCMD_DATE_LIVRAISON", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public DateTime? TCMD_DATE_LIVRAISON { get; set; }

        //[DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "g")]
        [Display(Name = "Display_TCMD_COMMANDES_TCMD_DATE_CLOTURE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public DateTime? TCMD_DATE_CLOTURE { get; set; }
 
        [Required]
        [Display(Name = "Display_TCMD_COMMANDES_TRU_COMMANDITAIREID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRU_COMMANDITAIREID { get; set; }

        [Display(Name = "Display_TCMD_COMMANDES_TRU_EXPLOITANTID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TRU_EXPLOITANTID { get; set; }

        //[Required]
        [Display(Name = "Display_TCMD_COMMANDES_TCMD_COMMENTAIRE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public string TCMD_COMMENTAIRE { get; set; }

        [Display(Name = "Display_TCMD_COMMANDES_TCMD_PH_PHASEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TCMD_PH_PHASEID { get; set; }

        [Display(Name = "Display_TCMD_COMMANDES_TCMD_ORIGINEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TCMD_ORIGINEID { get; set; }

        [Required]
        [Display(Name = "Display_TCMD_COMMANDES_TCMD_MC_MODE_CREATIONID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int TCMD_MC_MODE_CREATIONID { get; set; }

        [Display(Name = "Display_TCMD_COMMANDES_TDOM_DOMAINEID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TDOM_DOMAINEID { get; set; }

        [Display(Name = "Display_TCMD_COMMANDES_TE_ETATID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TE_ETATID { get; set; }
        
        [Display(Name = "Display_TCMD_COMMANDES_TS_SCENARIOID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        public int? TS_SCENARIOID { get; set; }




        [ForeignKey("TCMD_MC_MODE_CREATIONID")]
        [InverseProperty("TCMD_COMMANDES")]
        public virtual TCMD_MC_MODE_CREATIONS TCMD_MC_MODE_CREATION { get; set; }
        [ForeignKey("TCMD_ORIGINEID")]
        [InverseProperty("InverseTCMD_ORIGINE")]
        public virtual TCMD_COMMANDES TCMD_ORIGINE { get; set; }
       
        [ForeignKey("TCMD_PH_PHASEID")]
        [InverseProperty("TCMD_COMMANDES")]
        public virtual TCMD_PH_PHASES TCMD_PH_PHASE { get; set; }

        [ForeignKey(nameof(TRU_COMMANDITAIREID))]
        [InverseProperty(nameof(TRU_USERS.TCMD_COMMANDES_TRU_COMMANDITAIRE))]
        public virtual TRU_USERS TRU_COMMANDITAIRE { get; set; }

        [ForeignKey(nameof( TRU_EXPLOITANTID))]
        [InverseProperty(nameof(TRU_USERS.TCMD_COMMANDES_TRU_EXPLOITANT))]
        public virtual TRU_USERS TRU_EXPLOITANT { get; set; }


        [ForeignKey(nameof(TE_ETATID))]
        [InverseProperty(nameof(TE_ETATS.TCMD_COMMANDES_TE_ETAT))]
        public virtual TE_ETATS TE_ETAT { get; set; }

        [ForeignKey(nameof(TS_SCENARIOID))]
        [InverseProperty(nameof(TS_SCENARIOS.TCMD_COMMANDES_TS_SCENARIO))]
        public virtual TS_SCENARIOS TS_SCENARIO { get; set; }



        //enfant
        [InverseProperty("TCMD_ORIGINE")]
        public virtual ICollection<TCMD_COMMANDES> InverseTCMD_ORIGINE { get; set; }
      
        [InverseProperty("TCMD_COMMANDE")]
        public virtual ICollection<TCMD_DA_DEMANDES_ASSOCIEES> TCMD_DA_DEMANDES_ASSOCIEES { get; set; }
       
        [InverseProperty("TCMD_COMMANDE")]
        public virtual ICollection<TCMD_DOC_DOCUMENTS> TCMD_DOC_DOCUMENTS { get; set; }
        
        [InverseProperty("TCMD_COMMANDE")]
        public virtual ICollection<TCMD_SP_SUIVI_PHASES> TCMD_SP_SUIVI_PHASES { get; set; }

        [InverseProperty("TCMD_COMMANDE")]
        public virtual ICollection<TDC_DEMANDES_COMMANDES> TDC_DEMANDES_COMMANDES { get; set; }


    }
}