// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Krialys.Data.EF.Univers
{
    public partial class TCMD_MC_MODE_CREATIONS
    {
        public TCMD_MC_MODE_CREATIONS()
        {
            TCMD_COMMANDES = new HashSet<TCMD_COMMANDES>();
        }
        [Display(Name = "Display_TCMD_MC_MODE_CREATIONS_TCMD_MC_MODE_CREATIONID", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Key]
        public int TCMD_MC_MODE_CREATIONID { get; set; }

        [Display(Name = "Display_TCMD_MC_MODE_CREATIONS_TCMD_MC_CODE", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        public string TCMD_MC_CODE { get; set; }

        [Display(Name = "Display_TCMD_MC_MODE_CREATIONS_TCMD_MC_LIB_FR", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        public string TCMD_MC_LIB_FR { get; set; }

        [Display(Name = "Display_TCMD_MC_MODE_CREATIONS_TCMD_MC_LIB_EN", ResourceType = typeof(Resources.DataAnnotationsResources))]
        [Required]
        public string TCMD_MC_LIB_EN { get; set; }

        [InverseProperty("TCMD_MC_MODE_CREATION")]
        public virtual ICollection<TCMD_COMMANDES> TCMD_COMMANDES { get; set; }
    }


    /// <summary>
    /// Order creation modes.
    /// </summary>
    public static class CreationModes
    {
        /// <summary>
        /// Code when order is based on UTD/DPU.
        /// </summary>
        public const string UTD = "UTD";

        /// <summary>
        /// Code when order is based on a domain.
        /// </summary>
        public const string Domain = "DOM";

        /// <summary>
        /// Code when order is based on another order.
        /// </summary>
        public const string Copy = "CPY";
    }
}